 /*	espanol.cpp - Created by Giampiero Caprino
 
 This file is part of Train Director 3
 
 Train Director is free software; you can redistribute it and/or modify
 it under the terms of the GNU General Public License as published by
 the Free Software Foundation; using exclusively version 2.
 It is expressly forbidden the use of higher versions of the GNU
 General Public License.
 
 Train Director is distributed in the hope that it will be useful,
 but WITHOUT ANY WARRANTY; without even the implied warranty of
 MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 GNU General Public License for more details.
 
 You should have received a copy of the GNU General Public License
 along with Train Director; see the file COPYING.  If not, write to
 the Free Software Foundation, 59 Temple Place - Suite 330,
 Boston, MA 02111-1307, USA.
 */
namespace TrainDirPorting {
  public static partial class Globals {
    public static LocalizeInfo[] espanol = new LocalizeInfo[] {
 
 	new LocalizeInfo() { English = wxPorting.T("Arrival"), Other = wxPorting.T("Llegada") },
 	new LocalizeInfo() { English = wxPorting.T("From"), Other = wxPorting.T("De") },
 	new LocalizeInfo() { English = wxPorting.T("To"), Other = wxPorting.T("A") },
 	new LocalizeInfo() { English = wxPorting.T("Train"), Other = wxPorting.T("Tren") },
 	new LocalizeInfo() { English = wxPorting.T("Speed"), Other = wxPorting.T("Velocidad") },
 	new LocalizeInfo() { English = wxPorting.T("Min.Del."), Other = wxPorting.T("Ret.Ingr.") },
 	new LocalizeInfo() { English = wxPorting.T("Min.Late"), Other = wxPorting.T("Retraso") },
 	new LocalizeInfo() { English = wxPorting.T("Status"), Other = wxPorting.T("Estado") },
 
 	new LocalizeInfo() { English = wxPorting.T("Entry"), Other = wxPorting.T("Entrada") },
 	new LocalizeInfo() { English = wxPorting.T("Exit"), Other = wxPorting.T("Salida") },
 	new LocalizeInfo() { English = wxPorting.T("Entry/exit"), Other = wxPorting.T("Entrada/Salida") },
 	new LocalizeInfo() { English = wxPorting.T("Times"), Other = wxPorting.T("Hora") },
 
 	new LocalizeInfo() { English = wxPorting.T("Performance Statistics"), Other = wxPorting.T("Estadistica") },
 	new LocalizeInfo() { English = wxPorting.T("Save"), Other = wxPorting.T("Guardar") },
 
 	new LocalizeInfo() { English = wxPorting.T("Departing trains"), Other = wxPorting.T("Trenes saliendo") },
 	new LocalizeInfo() { English = wxPorting.T("Train Schedule"), Other = wxPorting.T("Horario del tren") },
 
 	new LocalizeInfo() { English = wxPorting.T("Close"), Other = wxPorting.T("Cerrar") },
 	new LocalizeInfo() { English = wxPorting.T("Stats"), Other = wxPorting.T("Estadíst.") },
 	new LocalizeInfo() { English = wxPorting.T("Print..."), Other = wxPorting.T("Imprimir...") },
 	new LocalizeInfo() { English = wxPorting.T("Assign"), Other = wxPorting.T("Asignar") },
 	new LocalizeInfo() { English = wxPorting.T("Shunt"), Other = wxPorting.T("Maniobra") },
 	new LocalizeInfo() { English = wxPorting.T("Cancel"), Other = wxPorting.T("Cancelar") },
 	new LocalizeInfo() { English = wxPorting.T("Properties"), Other = wxPorting.T("Propiedades") },
 	new LocalizeInfo() { English = wxPorting.T("Hide/Show titles"), Other = wxPorting.T("Esconder/Mostrar títulos") },
 
 	new LocalizeInfo() { English = wxPorting.T("Name"), Other = wxPorting.T("Nombre") },
 	new LocalizeInfo() { English = wxPorting.T("Sections"), Other = wxPorting.T("Sección") },
 
 	new LocalizeInfo() { English = wxPorting.T("Track properties"), Other = wxPorting.T("Propriedad del tramo") },
 	new LocalizeInfo() { English = wxPorting.T("Track %d,%d"), Other = wxPorting.T("Tramo %d,%d") },
 	new LocalizeInfo() { English = wxPorting.T("Length :"), Other = wxPorting.T("Longitud ") },
 	new LocalizeInfo() { English = wxPorting.T("Speed :"), Other = wxPorting.T("Velocidad") },
 	new LocalizeInfo() { English = wxPorting.T("Station :"), Other = wxPorting.T("Estación") },
 	new LocalizeInfo() { English = wxPorting.T("Linked to west :"), Other = wxPorting.T("Asociar al oeste :") },
 	new LocalizeInfo() { English = wxPorting.T("Controls :"), Other = wxPorting.T("Controles") },
 	new LocalizeInfo() { English = wxPorting.T("Linked to east :"), Other = wxPorting.T("Asociar al este :") },
 
 	new LocalizeInfo() { English = wxPorting.T("Trigger"), Other = wxPorting.T("Pedal") },
 	new LocalizeInfo() { English = wxPorting.T("Trigger properties"), Other = wxPorting.T("Propiedades pedal") },
 	new LocalizeInfo() { English = wxPorting.T("Trigger at  %d,%d"), Other = wxPorting.T("Pedal a  %d,%d") },
 	new LocalizeInfo() { English = wxPorting.T("Action :"), Other = wxPorting.T("Acción :") },
 	new LocalizeInfo() { English = wxPorting.T("'@' in action = name of triggering train"), Other = wxPorting.T("'@' en acción = nombre del tren activante") },
 	new LocalizeInfo() { English = wxPorting.T("Linked to track at coord:"), Other = wxPorting.T("Asociar al tramo :") },
 	new LocalizeInfo() { English = wxPorting.T("Probabilities for action :"), Other = wxPorting.T("Probabilidades de la acción :") },
 
 	new LocalizeInfo() { English = wxPorting.T("Signal properties"), Other = wxPorting.T("Propiedades de la señal") },
 	new LocalizeInfo() { English = wxPorting.T("Signal at %d,%d"), Other = wxPorting.T("Señal en %d,%d") },
 	new LocalizeInfo() { English = wxPorting.T("Signal Name :"), Other = wxPorting.T("Nombre de la señal") },
 	new LocalizeInfo() { English = wxPorting.T("Signal is always red"), Other = wxPorting.T("Señal siempre roja") },
 	new LocalizeInfo() { English = wxPorting.T("Signal has square frame"), Other = wxPorting.T("Señal de forma cuadrada") },
 	new LocalizeInfo() { English = wxPorting.T("No penalty for train stopping at this signal"), Other = wxPorting.T("No penalizar trenes parados en la señal") },
 
 	new LocalizeInfo() { English = wxPorting.T("Territory Information"), Other = wxPorting.T("Información del territorio") },
 	new LocalizeInfo() { English = wxPorting.T("Update"), Other = wxPorting.T("Actualizar") },
 	new LocalizeInfo() { English = wxPorting.T("Print"), Other = wxPorting.T("Imprimir") },
 
 	new LocalizeInfo() { English = wxPorting.T("Schedule"), Other = wxPorting.T("Horario") },
 	new LocalizeInfo() { English = wxPorting.T("Alerts"), Other = wxPorting.T("Alertas") },
 	new LocalizeInfo() { English = wxPorting.T("Train Info"), Other = wxPorting.T("Información del tren") },
 
 	new LocalizeInfo() { English = wxPorting.T("Day Selection"), Other = wxPorting.T("Elija día") },
 	new LocalizeInfo() { English = wxPorting.T("Not all trains run every day of the week.nWhich day do you want to simulate?"), Other = wxPorting.T("No todos los trenes circulan todos los días¿Qué día quiere simular?") },
 	new LocalizeInfo() { English = wxPorting.T("Monday"), Other = wxPorting.T("Lunes") },
 	new LocalizeInfo() { English = wxPorting.T("Tuesday"), Other = wxPorting.T("Martes") },
 	new LocalizeInfo() { English = wxPorting.T("Wednesday"), Other = wxPorting.T("Miércoles") },
 	new LocalizeInfo() { English = wxPorting.T("Thursday"), Other = wxPorting.T("Jueves") },
 	new LocalizeInfo() { English = wxPorting.T("Friday"), Other = wxPorting.T("Viernes") },
 	new LocalizeInfo() { English = wxPorting.T("Saturday"), Other = wxPorting.T("Sábado") },
 	new LocalizeInfo() { English = wxPorting.T("Sunday"), Other = wxPorting.T("Domingo") },
 	new LocalizeInfo() { English = wxPorting.T("Mon"), Other = wxPorting.T("Lun") },
 	new LocalizeInfo() { English = wxPorting.T("Tue"), Other = wxPorting.T("Mar") },
 	new LocalizeInfo() { English = wxPorting.T("Wed"), Other = wxPorting.T("Mié") },
 	new LocalizeInfo() { English = wxPorting.T("Thu"), Other = wxPorting.T("Jue") },
 	new LocalizeInfo() { English = wxPorting.T("Fri"), Other = wxPorting.T("Vie") },
 	new LocalizeInfo() { English = wxPorting.T("Sat"), Other = wxPorting.T("Sáb") },
 	new LocalizeInfo() { English = wxPorting.T("Sun"), Other = wxPorting.T("Dom") },
 
 	new LocalizeInfo() { English = wxPorting.T("Write default preferences to ini file?"), Other = wxPorting.T("¿Escribir las preferencias en el archivo ini?") },
 	new LocalizeInfo() { English = wxPorting.T("Preferences"), Other = wxPorting.T("Preferencias") },
 	new LocalizeInfo() { English = wxPorting.T("Full status info"), Other = wxPorting.T("Información del estado completo") },
 	new LocalizeInfo() { English = wxPorting.T("Status line at top of window"), Other = wxPorting.T("Línea de estado arriba") },
 	new LocalizeInfo() { English = wxPorting.T("Alert sound on"), Other = wxPorting.T("Sonido de aviso activado") },
 	new LocalizeInfo() { English = wxPorting.T("Beep on train entering scenario"), Other = wxPorting.T("Sonería al entrar un tren") },
 	new LocalizeInfo() { English = wxPorting.T("View speed limits"), Other = wxPorting.T("Mostrar límite de velocidad") },
 	new LocalizeInfo() { English = wxPorting.T("Automatically link signals"), Other = wxPorting.T("Asociar señales automáticamente") },
 	new LocalizeInfo() { English = wxPorting.T("Show grid"), Other = wxPorting.T("Mostrar cuadrícula") },
 	new LocalizeInfo() { English = wxPorting.T("View long blocks"), Other = wxPorting.T("Mostrar tramos largos") },
 	new LocalizeInfo() { English = wxPorting.T("Show seconds on clock"), Other = wxPorting.T("Mostrar los segundos en el reloj") },
 	new LocalizeInfo() { English = wxPorting.T("Italian signals"), Other = wxPorting.T("Señales italianas") },
 	new LocalizeInfo() { English = wxPorting.T("Hard performance tracking"), Other = wxPorting.T("Control estricto rendimiento") },
 	new LocalizeInfo() { English = wxPorting.T("Save preferences on exit"), Other = wxPorting.T("Guardar configuración al salir") },
 
 	new LocalizeInfo() { English = wxPorting.T("Itinerary"), Other = wxPorting.T("Trayecto") },
 	new LocalizeInfo() { English = wxPorting.T("Name :"), Other = wxPorting.T("Nombre :") },
 	new LocalizeInfo() { English = wxPorting.T("From signal '%s'"), Other = wxPorting.T("Desde señal '%s'") },
 	new LocalizeInfo() { English = wxPorting.T("Next itinerary :"), Other = wxPorting.T("Siguiente trayecto") },
 
 	new LocalizeInfo() { English = wxPorting.T("Performance status"), Other = wxPorting.T("Sumario configuración") },
 	new LocalizeInfo() { English = wxPorting.T("Wrong destinations :"), Other = wxPorting.T("Errores en el destino :") },
 	new LocalizeInfo() { English = wxPorting.T("Late trains :"), Other = wxPorting.T("Trenes retrasados :") },
 	new LocalizeInfo() { English = wxPorting.T("Thrown switches :"), Other = wxPorting.T("Errores al cambiar las agujas :") },
 	new LocalizeInfo() { English = wxPorting.T("Cleared signals :"), Other = wxPorting.T("Errores al cambiar a verde las señales :") },
 	new LocalizeInfo() { English = wxPorting.T("Turned trains :"), Other = wxPorting.T("Errores al invertir la dirección :") },
 	new LocalizeInfo() { English = wxPorting.T("Trains stopped at sig.:"), Other = wxPorting.T("Trenes parados en señales :") },
 	new LocalizeInfo() { English = wxPorting.T("Wrong platforms :"), Other = wxPorting.T("Andenes erróneos :") },
 	new LocalizeInfo() { English = wxPorting.T("Commands denied :"), Other = wxPorting.T("Acción denegada :") },
 	new LocalizeInfo() { English = wxPorting.T("Wrong stock assignments :"), Other = wxPorting.T("Asignación de material erróneo :") },
 
 	new LocalizeInfo() { English = wxPorting.T("Created by"), Other = wxPorting.T("Creado por") },
 	new LocalizeInfo() { English = wxPorting.T("This is a game, and is not intended tonbe used to actually control train traffic."), Other = wxPorting.T("Esto es un juego, y no es su intencion nel ser usado para el control real de tráfico ferroviario.") },
 	new LocalizeInfo() { English = wxPorting.T("This is free software, released under thenGNU General Public License."), Other = wxPorting.T(" Esto es un programa gratuito, distribuido bajo la licencia nGNU General Public License.") },
 	new LocalizeInfo() { English = wxPorting.T("This is free software, released under thenGNU General Public License.nThe author declines any responsibility for any damagenthat might occur from the use of this program."), Other = wxPorting.T(" Esto es un programa gratuito, distribuido bajo la licencia nGNU General Public License. El autor declina cualquier responsabilidad por cualquier dañonque pueda ocurrir por el uso de este programa.") },
 	new LocalizeInfo() { English = wxPorting.T("This is free software, released under thenGNU General Public License Version 2.nThe author declines any responsibility for any damagenthat might occur from the use of this program."), Other = wxPorting.T(" Esto es un programa gratuito, distribuido bajo la licencia nGNU General Public License Version 2. nEl autor declina cualquier responsabilidad por cualquier dañonque pueda ocurrir por el uso de este programa.") },
 
 	new LocalizeInfo() { English = wxPorting.T("Layout Errors"), Other = wxPorting.T("Errores en el escenário") },
 	new LocalizeInfo() { English = wxPorting.T("These trains will be delayed on entry:"), Other = wxPorting.T("Estos trenes entrarán con retraso:") },
 	new LocalizeInfo() { English = wxPorting.T("%s and %s both enter at %s on %s"), Other = wxPorting.T("Y %s che %s entran en %s en %s") },
 	new LocalizeInfo() { English = wxPorting.T("These trains have unknown entry or exit points:"), Other = wxPorting.T("Estos trenes tienen un punto de entrada o salida desconocido") },
 	new LocalizeInfo() { English = wxPorting.T("%s enters from '%s', exits at '%s'"), Other = wxPorting.T("'%s' entra por '%s', sale por '%s'") },
 
 	new LocalizeInfo() { English = wxPorting.T("Some train has unknown entry/exit point!"), Other = wxPorting.T("¡Algunos trenes tienen punto de entrada/salida desconocido!") },
 	new LocalizeInfo() { English = wxPorting.T("at"), Other = wxPorting.T("en") },
 
 
 	new LocalizeInfo() { English = wxPorting.T("Start"), Other = wxPorting.T("Iniciar") },
 	new LocalizeInfo() { English = wxPorting.T("Fast"), Other = wxPorting.T("Rápido") },
 	new LocalizeInfo() { English = wxPorting.T("Slow"), Other = wxPorting.T("Lento") },
 	new LocalizeInfo() { English = wxPorting.T("Sched."), Other = wxPorting.T("Horario") },
 
 	new LocalizeInfo() { English = wxPorting.T("Simulation results"), Other = wxPorting.T("Resultado de la simulación") },
 	new LocalizeInfo() { English = wxPorting.T("Time"), Other = wxPorting.T("Hora") },
 	new LocalizeInfo() { English = wxPorting.T("Total points"), Other = wxPorting.T("Puntuación total") },
 	new LocalizeInfo() { English = wxPorting.T("Total min. of delayed entry"), Other = wxPorting.T("Minutos totales de retraso en la entrada") },
 	new LocalizeInfo() { English = wxPorting.T("Total min. trains arrived late"), Other = wxPorting.T("Minutos totales de retraso en la llegada") },
 	new LocalizeInfo() { English = wxPorting.T("Total performance penalties"), Other = wxPorting.T("Penalizaciones totales") },
 	new LocalizeInfo() { English = wxPorting.T("Wrong destinatios"), Other = wxPorting.T("Destinos erróneos") },
 	new LocalizeInfo() { English = wxPorting.T("Late trains"), Other = wxPorting.T("Trenes retrasados") },
 	new LocalizeInfo() { English = wxPorting.T("Wrong platforms"), Other = wxPorting.T("Errores en el andén") },
 	new LocalizeInfo() { English = wxPorting.T("Commands denied"), Other = wxPorting.T("Acciones denegadas") },
 	new LocalizeInfo() { English = wxPorting.T("Trains waiting at signals"), Other = wxPorting.T("Trenes esperando en señal") },
 	new LocalizeInfo() { English = wxPorting.T("Thrown switches"), Other = wxPorting.T("Errores al cambiar de agujas") },
 	new LocalizeInfo() { English = wxPorting.T("Cleared signals"), Other = wxPorting.T("Errores al cambiar a verde una señal") },
 	new LocalizeInfo() { English = wxPorting.T("Wrong stock assignments"), Other = wxPorting.T("Errores en la asignación de material") },
 	new LocalizeInfo() { English = wxPorting.T("Reversed trains"), Other = wxPorting.T("Errores al invertir dirección") },
 
 	new LocalizeInfo() { English = wxPorting.T("Enters"), Other = wxPorting.T("Entradas") },
 	new LocalizeInfo() { English = wxPorting.T("At"), Other = wxPorting.T("En") },
 	new LocalizeInfo() { English = wxPorting.T("Exits"), Other = wxPorting.T("Salidas") },
 	new LocalizeInfo() { English = wxPorting.T("Before"), Other = wxPorting.T("Antes") },
 	new LocalizeInfo() { English = wxPorting.T("Delay"), Other = wxPorting.T("Retraso entrada") },
 	new LocalizeInfo() { English = wxPorting.T("Late"), Other = wxPorting.T("Retraso") },
 	new LocalizeInfo() { English = wxPorting.T("Status"), Other = wxPorting.T("Estado") },
 
 	new LocalizeInfo() { English = wxPorting.T("Station"), Other = wxPorting.T("Estación") },
 	new LocalizeInfo() { English = wxPorting.T("Arrival"), Other = wxPorting.T("Llegada") },
 	new LocalizeInfo() { English = wxPorting.T("Departure"), Other = wxPorting.T("Salida") },
 	new LocalizeInfo() { English = wxPorting.T("Min.stop"), Other = wxPorting.T("Minutos parada") },
 	new LocalizeInfo() { English = wxPorting.T("Plat."), Other = wxPorting.T("Andén") },
 	new LocalizeInfo() { English = wxPorting.T("Runs on"), Other = wxPorting.T("Circula el") },
 	new LocalizeInfo() { English = wxPorting.T("Notes"), Other = wxPorting.T("Notas") },
 	new LocalizeInfo() { English = wxPorting.T("To&nbsp;&nbsp;"), Other = wxPorting.T("De&nbsp;&nbsp;") },
 	new LocalizeInfo() { English = wxPorting.T("To&nbsp;&nbsp;&nbsp;"), Other = wxPorting.T("De&nbsp;&nbsp;&nbsp;") },
 	new LocalizeInfo() { English = wxPorting.T("Runs on&nbsp;&nbsp;"), Other = wxPorting.T("Circula el&nbsp;") },
 	new LocalizeInfo() { English = wxPorting.T("Runs&nbsp;on&nbsp;&nbsp;"), Other = wxPorting.T("Circula&nbsp;el&nbsp;") },
 	new LocalizeInfo() { English = wxPorting.T("Minimum stop (sec)"), Other = wxPorting.T("Parada mínima (sec)") },
 
 	new LocalizeInfo() { English = wxPorting.T("Territory"), Other = wxPorting.T("Territorio") },
 
 	new LocalizeInfo() { English = wxPorting.T("Are you sure you want to restorenthe simulation to its saved state?"), Other = wxPorting.T("¿Está seguro que quiere restaurarnla simulación a su estado inicial guardado?") },
 	new LocalizeInfo() { English = wxPorting.T("This will delete the current layout.nAre you sure you want to continue?"), Other = wxPorting.T("Esta acción borrará el escenario actual. ¿Seguro que quiere continuar?") },
 	new LocalizeInfo() { English = wxPorting.T("Replay interrupted."), Other = wxPorting.T("Reinicio interrumpido.") },
 
 
 	new LocalizeInfo() { English = wxPorting.T("/File/Open recent"), Other = wxPorting.T("/Archivo/Abrir recientes") },
 
 	new LocalizeInfo() { English = wxPorting.T("Train %s waiting at %d,%d!"), Other = wxPorting.T("Tren %s esperando en %d,%d!") },
 	new LocalizeInfo() { English = wxPorting.T("Train %s waiting at"), Other = wxPorting.T("Tren %s esperando en") },
 	new LocalizeInfo() { English = wxPorting.T("You must assign train %s using stock from train %s!"), Other = wxPorting.T("Debes reasignar el tren %s usando el material del tren %s!") },
 	new LocalizeInfo() { English = wxPorting.T("Train %s derailed at %s!"), Other = wxPorting.T("Tren %s descarrilado en %s!") },
 	new LocalizeInfo() { English = wxPorting.T("Train %s derailed at %d,%d!"), Other = wxPorting.T("Tren %s descarrilado en %d,%d!") },
 	new LocalizeInfo() { English = wxPorting.T("Train %s derailed!"), Other = wxPorting.T("Tren %s descarrilado") },
 	new LocalizeInfo() { English = wxPorting.T("Train %s delayed at %s!"), Other = wxPorting.T("Tren %s retrasado en %s!") },
 	new LocalizeInfo() { English = wxPorting.T("Cannot reverse direction. Path is busy."), Other = wxPorting.T("Imposible invertir dirección. Vía ocupada.") },
 	new LocalizeInfo() { English = wxPorting.T("This signal cannot be turned to green!"), Other = wxPorting.T("¡Esta señal no se puede cambiar a verde!") },
 	new LocalizeInfo() { English = wxPorting.T("You must wait for train to stop."), Other = wxPorting.T("Debes esperar a que el tren se detenga.") },
 	new LocalizeInfo() { English = wxPorting.T("Reverse train direction?"), Other = wxPorting.T("¿Invertir la dirección del tren?") },
 	new LocalizeInfo() { English = wxPorting.T("Proceed to next station?"), Other = wxPorting.T("¿Avanzar a la siguiente estación?") },
 
 	new LocalizeInfo() { English = wxPorting.T("Sorry, this feature is not available on this scenario."), Other = wxPorting.T("Lo siento, esta función no está disponible en este escenario.") },
 	new LocalizeInfo() { English = wxPorting.T("No station has distance information."), Other = wxPorting.T("Ninguna estación tiene información de la distancia.") },
 	new LocalizeInfo() { English = wxPorting.T("Train Schedule Graph"), Other = wxPorting.T("Grafico hOrario") },
 
 	new LocalizeInfo() { English = wxPorting.T("Error reading"), Other = wxPorting.T("Error al leer") },
 	new LocalizeInfo() { English = wxPorting.T("Final stop"), Other = wxPorting.T("Última parada") },
 	new LocalizeInfo() { English = wxPorting.T("at"), Other = wxPorting.T("en") },
 	new LocalizeInfo() { English = wxPorting.T("Next stop"), Other = wxPorting.T("Siguiente parada") },
 	new LocalizeInfo() { English = wxPorting.T("ready"), Other = wxPorting.T("listo") },
 	new LocalizeInfo() { English = wxPorting.T("Canceled - runs on"), Other = wxPorting.T("Suprimido - circula el") },
 	new LocalizeInfo() { English = wxPorting.T("Shunting"), Other = wxPorting.T("Maniobra") },
 	new LocalizeInfo() { English = wxPorting.T("to"), Other = wxPorting.T("a") },
 	new LocalizeInfo() { English = wxPorting.T("Running. Dest."), Other = wxPorting.T("Circulando. Dest.") },
 	new LocalizeInfo() { English = wxPorting.T("Stopped. ETD"), Other = wxPorting.T("Parado. ETD") },
 	new LocalizeInfo() { English = wxPorting.T("Dest."), Other = wxPorting.T("Dest.") },
 	new LocalizeInfo() { English = wxPorting.T("Delayed entry at"), Other = wxPorting.T("Entrada retrasada en") },
 	new LocalizeInfo() { English = wxPorting.T("Waiting"), Other = wxPorting.T("Esperando") },
 	new LocalizeInfo() { English = wxPorting.T("derailed"), Other = wxPorting.T("descarrilado") },
 	new LocalizeInfo() { English = wxPorting.T("Arrived at"), Other = wxPorting.T("Llegó a") },
 	new LocalizeInfo() { English = wxPorting.T("instead of"), Other = wxPorting.T("En vez de a") },
 	new LocalizeInfo() { English = wxPorting.T("Arrived"), Other = wxPorting.T("Llegada") },
 	new LocalizeInfo() { English = wxPorting.T("min. late at"), Other = wxPorting.T("min. de retraso en") },
 	new LocalizeInfo() { English = wxPorting.T("Arrived on time"), Other = wxPorting.T("Llegada a tiempo") },
 	new LocalizeInfo() { English = wxPorting.T("stock for"), Other = wxPorting.T("Asignar a") },
 
 	new LocalizeInfo() { English = wxPorting.T("Signal at"), Other = wxPorting.T("Señal en") },
 	new LocalizeInfo() { English = wxPorting.T("not linked to any track"), Other = wxPorting.T("no asociado a ningún tramo") },
 	new LocalizeInfo() { English = wxPorting.T("Track at"), Other = wxPorting.T("Tramo en") },
 	new LocalizeInfo() { English = wxPorting.T("not controlled by signal at"), Other = wxPorting.T("no controlado por señal en") },
 	new LocalizeInfo() { English = wxPorting.T("linked to non-existant track at"), Other = wxPorting.T("Asociado a un tramo inexistente") },
 	new LocalizeInfo() { English = wxPorting.T("not linked back to"), Other = wxPorting.T("No reasociado a") },
 	new LocalizeInfo() { English = wxPorting.T("Switch at"), Other = wxPorting.T("Cambio en") },
 	new LocalizeInfo() { English = wxPorting.T("linked to non-existant switch at"), Other = wxPorting.T("Asociado a un cambio inexistente en") },
 	new LocalizeInfo() { English = wxPorting.T("not linked back to switch at"), Other = wxPorting.T("no reasociado al cambio en") },
 	new LocalizeInfo() { English = wxPorting.T("Checking for errors in layout...n"), Other = wxPorting.T("Buscando errores en la ruta...n") },
 	new LocalizeInfo() { English = wxPorting.T("nly like tracks can be linked."), Other = wxPorting.T("Sólo tramos compatibles pueden ser asociados.") },
 	new LocalizeInfo() { English = wxPorting.T("Only horizontal or vertical tracks can be linked automatically."), Other = wxPorting.T("Sólo tramos horizontales o verticales pueden ser asociados automáticamente. Para asociar otros tipos de tramos, usar \"propiedades\".") },
 	new LocalizeInfo() { English = wxPorting.T("Signals can only be linked to a track."), Other = wxPorting.T("Una señal sólo puede ser asociada a un tramo.") },
 	new LocalizeInfo() { English = wxPorting.T("Triggers can only be linked to a track."), Other = wxPorting.T("Un pedal sólo puede ser asociada a un tramo.") },
 	new LocalizeInfo() { English = wxPorting.T("Entry/Exit point can only be linked to a track."), Other = wxPorting.T("Un punto de entrada/salida sólo puede ser asociado a un tramo.") },
 
 	new LocalizeInfo() { English = wxPorting.T("speed"), Other = wxPorting.T("veloc.") },
 	new LocalizeInfo() { English = wxPorting.T("length"), Other = wxPorting.T("longit.") },
 	new LocalizeInfo() { English = wxPorting.T("Station"), Other = wxPorting.T("Estación") },
 	new LocalizeInfo() { English = wxPorting.T("entry/exit"), Other = wxPorting.T("entrada/salida") },
 	new LocalizeInfo() { English = wxPorting.T("Signal"), Other = wxPorting.T("Señal") },
 	new LocalizeInfo() { English = wxPorting.T("controls"), Other = wxPorting.T("Controles") },
 
 	new LocalizeInfo() { English = wxPorting.T("Station of"), Other = wxPorting.T("Estación de") },
 	new LocalizeInfo() { English = wxPorting.T("Platform"), Other = wxPorting.T("Andén") },
 	new LocalizeInfo() { English = wxPorting.T("An itinerary by the same name already exists.nDo you want to replace the old itinerary with the new LocalizeInfo() one?"), Other = wxPorting.T("Un itinerario con el mismo nombre ya existe. ¿Quiere reemplazar el antiguo itinerario por este nuevo?") },
 
 	new LocalizeInfo() { English = wxPorting.T("Cannot create log file."), Other = wxPorting.T("Imposible crear el archivo log.") },
 	new LocalizeInfo() { English = wxPorting.T("Cannot read log file."), Other = wxPorting.T("Imposible leer el archivo log.") },
 	new LocalizeInfo() { English = wxPorting.T("Do you want to restart the simulation?"), Other = wxPorting.T("¿Quiere reiniciar la simulación desde el inicio?") },
 	new LocalizeInfo() { English = wxPorting.T("Simulation restarted."), Other = wxPorting.T("Simulación reiniciada desde le inicio.") },
 
 	new LocalizeInfo() { English = wxPorting.T("Stop"), Other = wxPorting.T("Parar") },
 	new LocalizeInfo() { English = wxPorting.T("Start"), Other = wxPorting.T("Iniciar") },
 	new LocalizeInfo() { English = wxPorting.T("Restart"), Other = wxPorting.T("Reiniciar") },
 	new LocalizeInfo() { English = wxPorting.T("Layout saved in file"), Other = wxPorting.T("Trayecto guardado en le archivo") },
 	new LocalizeInfo() { English = wxPorting.T("Game status saved in file"), Other = wxPorting.T("Estado del juego guardado en el archivo") },
 	new LocalizeInfo() { English = wxPorting.T("No schedule for this territory!"), Other = wxPorting.T("¡Horario inexistente para esta ruta!") },
 	new LocalizeInfo() { English = wxPorting.T("Question"), Other = wxPorting.T("Pregunta") },
 	new LocalizeInfo() { English = wxPorting.T("Warning"), Other = wxPorting.T("Atención") },
 	new LocalizeInfo() { English = wxPorting.T("Attention"), Other = wxPorting.T("Error") },
 	new LocalizeInfo() { English = wxPorting.T("Open File"), Other = wxPorting.T("Abrir archivo") },
 	new LocalizeInfo() { English = wxPorting.T("Error"), Other = wxPorting.T("Error") },
 	new LocalizeInfo() { English = wxPorting.T("Scenarios"), Other = wxPorting.T("Escenarios") },
 	new LocalizeInfo() { English = wxPorting.T("Saved games"), Other = wxPorting.T("Partida guardada") },
 	new LocalizeInfo() { English = wxPorting.T("All files (*.*)"), Other = wxPorting.T("Todos los archivos (*.*)") },
 	new LocalizeInfo() { English = wxPorting.T("Icons"), Other = wxPorting.T("Iconos") },
 	new LocalizeInfo() { English = wxPorting.T("Save File"), Other = wxPorting.T("Guardar archivo") },
 	new LocalizeInfo() { English = wxPorting.T("Can't create file"), Other = wxPorting.T("Imposible crear el archivo") },
 
 	new LocalizeInfo() { English = wxPorting.T("/_File"), Other = wxPorting.T("/_Archivo") },
 	new LocalizeInfo() { English = wxPorting.T("/File/_Open"), Other = wxPorting.T("/Archivo/_Abrir") },
 	new LocalizeInfo() { English = wxPorting.T("/File/Open re_cent"), Other = wxPorting.T("/Archivo/Abrir recientes") },
 	new LocalizeInfo() { English = wxPorting.T("/File/_Save Game"), Other = wxPorting.T("/Archivo/_Guardar partida") },
 	new LocalizeInfo() { English = wxPorting.T("/File/_Restore"), Other = wxPorting.T("/Archivo/_Restaurar") },
 	new LocalizeInfo() { English = wxPorting.T("/File/Save _As"), Other = wxPorting.T("/Archivo/Guardar _Como") },
 	new LocalizeInfo() { English = wxPorting.T("/File/_Log"), Other = wxPorting.T("/Archivo/Re_gistra") },
 	new LocalizeInfo() { English = wxPorting.T("/File/_Replay"), Other = wxPorting.T("/Archivo/_Repetir") },
 	new LocalizeInfo() { English = wxPorting.T("/File/About..."), Other = wxPorting.T("/Archivo/Información...") },
 	new LocalizeInfo() { English = wxPorting.T("/File/Quit"), Other = wxPorting.T("/Archivo/Cerrar") },
 	new LocalizeInfo() { English = wxPorting.T("/Edit/_Edit"), Other = wxPorting.T("/Editar/_Editar") },
 	new LocalizeInfo() { English = wxPorting.T("/Edit/_new LocalizeInfo() Train"), Other = wxPorting.T("/Editar/_Nuevo Tren") },
 	new LocalizeInfo() { English = wxPorting.T("/Edit/Itinerary"), Other = wxPorting.T("/Editar/Itinerario") },
 	new LocalizeInfo() { English = wxPorting.T("/Edit/_Save Layout"), Other = wxPorting.T("/Editar/_Guardar Ruta") },
 	new LocalizeInfo() { English = wxPorting.T("/Edit/_Preferences"), Other = wxPorting.T("/Editar/_Preferencias") },
 	new LocalizeInfo() { English = wxPorting.T("/Edit/_New"), Other = wxPorting.T("/Editar/_Nueva Ruta") },
 	new LocalizeInfo() { English = wxPorting.T("/Edit/_Info"), Other = wxPorting.T("/Editar/_Información") },
 	new LocalizeInfo() { English = wxPorting.T("/_Run"), Other = wxPorting.T("/_Simular") },
 	new LocalizeInfo() { English = wxPorting.T("/Run/_Start"), Other = wxPorting.T("/Simular/_Iniciar") },
 	new LocalizeInfo() { English = wxPorting.T("/Run/View _Graph"), Other = wxPorting.T("/Simular/Horario _Gráfico") },
 	new LocalizeInfo() { English = wxPorting.T("/Run/Restart"), Other = wxPorting.T("/Simular/Reiniciar") },
 	new LocalizeInfo() { English = wxPorting.T("/Run/_Fast"), Other = wxPorting.T("/Simular/_Rápido") },
 	new LocalizeInfo() { English = wxPorting.T("/Run/S_low"), Other = wxPorting.T("/Simular/_Lento") },
 	new LocalizeInfo() { English = wxPorting.T("/Run/S_tation schedule"), Other = wxPorting.T("/Simular/Horario de _Estaciones") },
 	new LocalizeInfo() { English = wxPorting.T("/Run/Set sig. to green"), Other = wxPorting.T("/Simular/Señales autom. a verde") },
 	new LocalizeInfo() { English = wxPorting.T("/Run/Performance"), Other = wxPorting.T("/Simular/Configuración") },
 
 	new LocalizeInfo() { English = wxPorting.T("This is a game, and is not intended tonbe used to actually control train traffic."), Other = wxPorting.T("Esto es un juego, y no es su intencion nel ser usado para el control real de tráfico ferroviario.") },
 	new LocalizeInfo() { English = wxPorting.T("This is free software, released under thenGNU General Public License Version 2."), Other = wxPorting.T(" Esto es un programa gratuito, distribuido bajo la licencia nGNU General Public License Version 2.") },
 	new LocalizeInfo() { English = wxPorting.T("The author declines any responsibility for any damagenthat might occur from the use of this program."), Other = wxPorting.T("El autor declina cualquier responsabilidad por cualquier dañonque pueda ocurrir por el uso de este programa.") },
 
 	new LocalizeInfo() { English = wxPorting.T("Assign rolling stock"), Other = wxPorting.T("Asignar material rodante") },
 	new LocalizeInfo() { English = wxPorting.T("&Assign"), Other = wxPorting.T("&Asignar") },
 	new LocalizeInfo() { English = wxPorting.T("S&hunt"), Other = wxPorting.T("&Maniobra") },
 	new LocalizeInfo() { English = wxPorting.T("Sp&lit"), Other = wxPorting.T("Desa&copla") },
 	new LocalizeInfo() { English = wxPorting.T("&Properties"), Other = wxPorting.T("&Propiedades") },
 	new LocalizeInfo() { English = wxPorting.T("&Cancel"), Other = wxPorting.T("&Cancelar") },
 
 	new LocalizeInfo() { English = wxPorting.T("Itinerary definition"), Other = wxPorting.T("Definición itinerario") },
 	new LocalizeInfo() { English = wxPorting.T("&Name"), Other = wxPorting.T("Nombre") },
 	new LocalizeInfo() { English = wxPorting.T("From signal"), Other = wxPorting.T("De la señal") },
 	new LocalizeInfo() { English = wxPorting.T("Ne&xt itinerary"), Other = wxPorting.T("&Siguiente itinerario") },
 
 	new LocalizeInfo() { English = wxPorting.T("Performance"), Other = wxPorting.T("Configuración") },
 	new LocalizeInfo() { English = wxPorting.T("Count"), Other = wxPorting.T("Frecuencia") },
 	new LocalizeInfo() { English = wxPorting.T("Points"), Other = wxPorting.T("Puntos") },
 	new LocalizeInfo() { English = wxPorting.T("Total"), Other = wxPorting.T("Total") },
 	new LocalizeInfo() { English = wxPorting.T("Wrong destinations"), Other = wxPorting.T("Destinos erróneos") },
 	new LocalizeInfo() { English = wxPorting.T("Late trains"), Other = wxPorting.T("Trenes llegados con retraso") },
 	new LocalizeInfo() { English = wxPorting.T("Wrong platforms"), Other = wxPorting.T("Errores de andén") },
 	new LocalizeInfo() { English = wxPorting.T("Commands denied"), Other = wxPorting.T("Acciones denegadas") },
 	new LocalizeInfo() { English = wxPorting.T("Trains stopped at signals"), Other = wxPorting.T("Trenes parados en señal") },
 	new LocalizeInfo() { English = wxPorting.T("Turned trains"), Other = wxPorting.T("Errores en la inversión del tren") },
 	new LocalizeInfo() { English = wxPorting.T("Thrown switches"), Other = wxPorting.T("Errores al cambiar de agujas") },
 	new LocalizeInfo() { English = wxPorting.T("Cleared signals"), Other = wxPorting.T("Errores al cambiar a verde una señal") },
 	new LocalizeInfo() { English = wxPorting.T("Wrong stock assignments"), Other = wxPorting.T("Errores al asignar el material") },
 
 
 	new LocalizeInfo() { English = wxPorting.T("Preferences"), Other = wxPorting.T("Preferencias") },
 	new LocalizeInfo() { English = wxPorting.T("Short train info"), Other = wxPorting.T("Información tren reducida") },
 	new LocalizeInfo() { English = wxPorting.T("Status line at top of window"), Other = wxPorting.T("Línea de estado arriba") },
 	new LocalizeInfo() { English = wxPorting.T("Alert sound on"), Other = wxPorting.T("Señal de aviso encendida") },
 	new LocalizeInfo() { English = wxPorting.T("Alert on train entering layout"), Other = wxPorting.T("Aviso sonoro al entrar un tren en el escenario") },
 	new LocalizeInfo() { English = wxPorting.T("View speed limits"), Other = wxPorting.T("Mostrar los puntos de límite de velocidad") },
 	new LocalizeInfo() { English = wxPorting.T("Automatically link signals"), Other = wxPorting.T("Asociar automáticamente las señales") },
 	new LocalizeInfo() { English = wxPorting.T("Show grid"), Other = wxPorting.T("Mostar cuadrícula") },
 	new LocalizeInfo() { English = wxPorting.T("View long blocks"), Other = wxPorting.T("Mostrarl longitud tramos") },
 	new LocalizeInfo() { English = wxPorting.T("Show seconds on clock"), Other = wxPorting.T("Mostrar los segundos en el reloj") },
 	new LocalizeInfo() { English = wxPorting.T("Traditional signals"), Other = wxPorting.T("Señales tradicionales") },
 	new LocalizeInfo() { English = wxPorting.T("Strong performance checking"), Other = wxPorting.T("Control más restrictivo de error") },
 	new LocalizeInfo() { English = wxPorting.T("Show linked objects in editor"), Other = wxPorting.T("Mostrar objetos asociados en el editor") },
 	new LocalizeInfo() { English = wxPorting.T("Check the desired options:"), Other = wxPorting.T("Seleccione la opción deseada:") },
 	new LocalizeInfo() { English = wxPorting.T("&Late GraphtCtrl-wxPorting.L"), Other = wxPorting.T("Retraso AcumuladotCtrl-wxPorting.L") },
 	new LocalizeInfo() { English = wxPorting.T("&Platform Graph"), Other = wxPorting.T("Ocupación de los Andenes ") },
 
 	new LocalizeInfo() { English = wxPorting.T("Day selection"), Other = wxPorting.T("Seleccione día") },
 	new LocalizeInfo() { English = wxPorting.T("&Continue"), Other = wxPorting.T("&Continuar") },
 
 	new LocalizeInfo() { English = wxPorting.T("Signal at coordinates :"), Other = wxPorting.T("Señal en coordenadas :") },
 	new LocalizeInfo() { English = wxPorting.T("Signal name :"), Other = wxPorting.T("Nombre señal") },
 	new LocalizeInfo() { English = wxPorting.T("Linked to east :"), Other = wxPorting.T("Asociado al este :") },
 	new LocalizeInfo() { English = wxPorting.T("Linked to west :"), Other = wxPorting.T("Asociado al oeste :") },
 	new LocalizeInfo() { English = wxPorting.T("Signal is always red"), Other = wxPorting.T("Señal siempre en rojo") },
 	new LocalizeInfo() { English = wxPorting.T("Signal has square frame"), Other = wxPorting.T("Señal de forma cuadrada") },
 	new LocalizeInfo() { English = wxPorting.T("No penalty for train stopping at this signal"), Other = wxPorting.T("No penalizar por trenes parados en esta señal") },
 
 	new LocalizeInfo() { English = wxPorting.T("S&tation scheduletF6"), Other = wxPorting.T("Horario de estacióntF6") },
 	new LocalizeInfo() { English = wxPorting.T("Station schedule"), Other = wxPorting.T("Horario de estación") },
 	new LocalizeInfo() { English = wxPorting.T("S&tation scheduletF5"), Other = wxPorting.T("Horario de es&tacióntF5") },
 	new LocalizeInfo() { English = wxPorting.T("&Schedule for station :"), Other = wxPorting.T("&Horario para la estación de :") },
 	new LocalizeInfo() { English = wxPorting.T("&Ignore platform number"), Other = wxPorting.T("&Ignorar andén de llegada") },
 	new LocalizeInfo() { English = wxPorting.T("&Close"), Other = wxPorting.T("&Cerrar") },
 	new LocalizeInfo() { English = wxPorting.T("&Print"), Other = wxPorting.T("&Imprimir") },
 
 	new LocalizeInfo() { English = wxPorting.T("Select ItinerarytCtrl-I"), Other = wxPorting.T("Seleccion ItinerariotCtrl-I") },
 	new LocalizeInfo() { English = wxPorting.T("Select Itinerary"), Other = wxPorting.T("Selecciona Itinerario") },
 	new LocalizeInfo() { English = wxPorting.T("Select itinerary"), Other = wxPorting.T("Selecciona itinerario") },
 
 	new LocalizeInfo() { English = wxPorting.T("Layout Information"), Other = wxPorting.T("Información del trayecto") },
 
 	new LocalizeInfo() { English = wxPorting.T("Track Properties"), Other = wxPorting.T("Propiedades del tramo") },
 	new LocalizeInfo() { English = wxPorting.T("Track Length (m) :"), Other = wxPorting.T("Longitud del tramo (m) :") },
 	new LocalizeInfo() { English = wxPorting.T("Station name :"), Other = wxPorting.T("Nombre Estación :") },
 	new LocalizeInfo() { English = wxPorting.T("Speed(s) :"), Other = wxPorting.T("Velocidad") },
 
 	new LocalizeInfo() { English = wxPorting.T("Train Properties"), Other = wxPorting.T("Propiedades del tren") },
 	new LocalizeInfo() { English = wxPorting.T("Train name"), Other = wxPorting.T("Nombre del tren") },
 	new LocalizeInfo() { English = wxPorting.T("Train type"), Other = wxPorting.T("Tipo de tren") },
 	new LocalizeInfo() { English = wxPorting.T("Entry point"), Other = wxPorting.T("Punto de entrada") },
 	new LocalizeInfo() { English = wxPorting.T("Entry time (hh:mm)"), Other = wxPorting.T("Horario de entrada (hh:mm)") },
 	new LocalizeInfo() { English = wxPorting.T("Exit point"), Other = wxPorting.T("Punto de salida") },
 	new LocalizeInfo() { English = wxPorting.T("Exit time (hh:mm)"), Other = wxPorting.T("Horario de salida (hh:mm)") },
 	new LocalizeInfo() { English = wxPorting.T("Wait arrival of train"), Other = wxPorting.T("Esperar llegada del tren") },
 	new LocalizeInfo() { English = wxPorting.T("Stock for train"), Other = wxPorting.T("Material para el tren") },
 	new LocalizeInfo() { English = wxPorting.T("Runs on"), Other = wxPorting.T("Circula el") },
 	new LocalizeInfo() { English = wxPorting.T("Train length :"), Other = wxPorting.T("Longitud del tren :") },
 
 	new LocalizeInfo() { English = wxPorting.T("Trigger Properties"), Other = wxPorting.T("Propiedad Pedal") },
 	new LocalizeInfo() { English = wxPorting.T("Trigger at coordinates :"), Other = wxPorting.T("Pedal a las coordenadas :") },
 	new LocalizeInfo() { English = wxPorting.T("Actionn(e.g. \"click 12,4\")"), Other = wxPorting.T("Acciónn(es. \"click 12,4\")") },
 	new LocalizeInfo() { English = wxPorting.T("Linked to track at :"), Other = wxPorting.T("Asociado al tramo en :") },
 	new LocalizeInfo() { English = wxPorting.T("Probabilities :"), Other = wxPorting.T("Probabilidades") },
 	new LocalizeInfo() { English = wxPorting.T("Action:             ('@' in action = name of triggering train)"), Other = wxPorting.T("Acción: ('@' en acción = nombre del tren activante)") },
 	new LocalizeInfo() { English = wxPorting.T("Linked to track at coord :"), Other = wxPorting.T("Asignar al tramo en coord. :") },
 	new LocalizeInfo() { English = wxPorting.T("Probabilities for action :"), Other = wxPorting.T("Probabilidad para la acción :") },
 
 	new LocalizeInfo() { English = wxPorting.T("cannot load"), Other = wxPorting.T("Imposible cargar") },
 	new LocalizeInfo() { English = wxPorting.T("Destination"), Other = wxPorting.T("Destino") },
 	new LocalizeInfo() { English = wxPorting.T("Assigning stock of train %s arrived at station %s"), Other = wxPorting.T("Asignar material del tren %s llegado a %s") },
 	new LocalizeInfo() { English = wxPorting.T("From signal '%s'"), Other = wxPorting.T("Desde la señal '%s'") },
 
 	new LocalizeInfo() { English = wxPorting.T("&File"), Other = wxPorting.T("&Archivo") },
 	new LocalizeInfo() { English = wxPorting.T("&Open...tCtrl-O"), Other = wxPorting.T("&Abrir...tCtrl-O") },
 	new LocalizeInfo() { English = wxPorting.T("&Save Game..."), Other = wxPorting.T("&Guardar Partida...") },
 	new LocalizeInfo() { English = wxPorting.T("&Restore..."), Other = wxPorting.T("&Restaurar simulación...") },
 	new LocalizeInfo() { English = wxPorting.T("Page set&up"), Other = wxPorting.T("Config&urar Página impresa") },
 	new LocalizeInfo() { English = wxPorting.T("Pre&view"), Other = wxPorting.T("Pre&ver la impresión") },
 	new LocalizeInfo() { English = wxPorting.T("&Print"), Other = wxPorting.T("Imprimir&pa") },
 	new LocalizeInfo() { English = wxPorting.T("&Edit"), Other = wxPorting.T("&Editar") },
 	new LocalizeInfo() { English = wxPorting.T("&Itinerary"), Other = wxPorting.T("&Itinerario") },
 	new LocalizeInfo() { English = wxPorting.T("&Save Layout"), Other = wxPorting.T("&Guardar Trayecto") },
 	new LocalizeInfo() { English = wxPorting.T("&Preferences..."), Other = wxPorting.T("&Preferencias") },
 	new LocalizeInfo() { English = wxPorting.T("ExittAlt-F4"), Other = wxPorting.T("SalirtAlt-F4") },
 	new LocalizeInfo() { English = wxPorting.T("Ne&w"), Other = wxPorting.T("&Nueva ruta") },
 	new LocalizeInfo() { English = wxPorting.T("In&fo"), Other = wxPorting.T("&Información") },
 	new LocalizeInfo() { English = wxPorting.T("&Run"), Other = wxPorting.T("&Simular") },
 	new LocalizeInfo() { English = wxPorting.T("&StarttCtrl-S"), Other = wxPorting.T("&IniciartCtrl-S") },
 	new LocalizeInfo() { English = wxPorting.T("&GraphtCtrl-G"), Other = wxPorting.T("Horario &GráficotCtrl-G") },
 	new LocalizeInfo() { English = wxPorting.T("&Restart..."), Other = wxPorting.T("&Reiniciar...") },
 	new LocalizeInfo() { English = wxPorting.T("&FasttCtrl-X"), Other = wxPorting.T("&RápidotCtrl-X") },
 	new LocalizeInfo() { English = wxPorting.T("&SlowtCtrl-Z"), Other = wxPorting.T("&LentotCtrl-Z") },
 	new LocalizeInfo() { English = wxPorting.T("Set sig. to green"), Other = wxPorting.T("Señales autom. a verde") },
 	new LocalizeInfo() { English = wxPorting.T("&Performance"), Other = wxPorting.T("Configuración") },
 
 	new LocalizeInfo() { English = wxPorting.T("&View"), Other = wxPorting.T("&Mostrar") },
 	new LocalizeInfo() { English = wxPorting.T("Show layouttF3"), Other = wxPorting.T("Mostrar trayectotF3") },
 	new LocalizeInfo() { English = wxPorting.T("Show scheduletF4"), Other = wxPorting.T("Mostrar horariotF4") },
 	new LocalizeInfo() { English = wxPorting.T("Timetable in split window"), Other = wxPorting.T("Horario en recuadro") },
 	new LocalizeInfo() { English = wxPorting.T("Timetable in tabbed window"), Other = wxPorting.T("Horario en panel") },
 	new LocalizeInfo() { English = wxPorting.T("Timetable in separate window"), Other = wxPorting.T("Horario en ventana separada") },
 	new LocalizeInfo() { English = wxPorting.T("Tool bar"), Other = wxPorting.T("Barra de herramientas") },
 	new LocalizeInfo() { English = wxPorting.T("Status bar"), Other = wxPorting.T("Línea de estado") },
 
 	new LocalizeInfo() { English = wxPorting.T("Welcome"), Other = wxPorting.T("Bienvenido") },
 	new LocalizeInfo() { English = wxPorting.T("WelcometF1"), Other = wxPorting.T("BienvenidotF1") },
 	new LocalizeInfo() { English = wxPorting.T("&Help"), Other = wxPorting.T("&Ayuda") },
 
 	new LocalizeInfo() { English = wxPorting.T("Tools"), Other = wxPorting.T("Herramientas") },
 	new LocalizeInfo() { English = wxPorting.T("Graph"), Other = wxPorting.T("Gráfico") },
 	new LocalizeInfo() { English = wxPorting.T("Layout"), Other = wxPorting.T("Trayecto") },
 
 	new LocalizeInfo() { English = wxPorting.T("You recently played the following simulations:<br><br>"), Other = wxPorting.T("Rutas simuladas recientemente:<br><br>") },
 	new LocalizeInfo() { English = wxPorting.T("Clear"), Other = wxPorting.T("Limpiar") },
 
 	new LocalizeInfo() { English = wxPorting.T("Remove all alerts from this list?"), Other = wxPorting.T("¿Eliminar todas las alertas de esta lista?") },
 	new LocalizeInfo() { English = wxPorting.T("Show Canceled"), Other = wxPorting.T("Mostrar suprimidos") },
 	new LocalizeInfo() { English = wxPorting.T("Track First Train"), Other = wxPorting.T("Seguir Primer Tren Activo") },
 	new LocalizeInfo() { English = wxPorting.T("Track Last Train"), Other = wxPorting.T("Seguir Último Tren Activo") },
 	new LocalizeInfo() { English = wxPorting.T("Show/hide canceled trains from list"), Other = wxPorting.T("Mostrar/esconder de la lista los trenes que no circulan") },
 	new LocalizeInfo() { English = wxPorting.T("Automatically show first active train in list"), Other = wxPorting.T("Mostrar automaticamente en la lista el primer tren activo") },
 	new LocalizeInfo() { English = wxPorting.T("Automatically show last active train in list"), Other = wxPorting.T("Mostrar automaticamente en la lista el último tren activo") },
 
 	new LocalizeInfo() { English = wxPorting.T("Stations &List"), Other = wxPorting.T("&Lista Estaciones") },
 	new LocalizeInfo() { English = wxPorting.T("Stations List"), Other = wxPorting.T("Lista Estaciones") },
 	new LocalizeInfo() { English = wxPorting.T("Stations and Entry/Exit Points"), Other = wxPorting.T("Estación y Punto de Entrada/Salida") },
 	new LocalizeInfo() { English = wxPorting.T("Station Name"), Other = wxPorting.T("Nombre estación") },
 	new LocalizeInfo() { English = wxPorting.T("Coordinates"), Other = wxPorting.T("Coordenadas") },
 	new LocalizeInfo() { English = wxPorting.T("Entry/Exit"), Other = wxPorting.T("Entrada/Salida") },
 
 	new LocalizeInfo() { English = wxPorting.T("Zoom in"), Other = wxPorting.T("Acercar") },
 	new LocalizeInfo() { English = wxPorting.T("Zoom out"), Other = wxPorting.T("Alejar") },
 	new LocalizeInfo() { English = wxPorting.T("Coord bars"), Other = wxPorting.T("Coordenadas") },
 
 	new LocalizeInfo() { English = wxPorting.T("Delete Column"), Other = wxPorting.T("Borrar Columna") },
 	new LocalizeInfo() { English = wxPorting.T("Delete Columns..."), Other = wxPorting.T("Borrar Columnas...") },
 	new LocalizeInfo() { English = wxPorting.T("Insert Column"), Other = wxPorting.T("Insertar Columna") },
 	new LocalizeInfo() { English = wxPorting.T("Insert Columns..."), Other = wxPorting.T("Inserar columnas...") },
 	new LocalizeInfo() { English = wxPorting.T("Delete Row"), Other = wxPorting.T("Borrar Fila") },
 	new LocalizeInfo() { English = wxPorting.T("Delete Rows..."), Other = wxPorting.T("Borrar Filas...") },
 	new LocalizeInfo() { English = wxPorting.T("Insert Row"), Other = wxPorting.T("Insertar Fila") },
 	new LocalizeInfo() { English = wxPorting.T("Insert Rows..."), Other = wxPorting.T("Insertar Filas...") },
 	new LocalizeInfo() { English = wxPorting.T("Delete"), Other = wxPorting.T("Borrar ") },
 	new LocalizeInfo() { English = wxPorting.T("Day"), Other = wxPorting.T("Día ") },
 	new LocalizeInfo() { English = wxPorting.T("Assign&+Shunt"), Other = wxPorting.T("Asigna&+Maniobra") },
 	new LocalizeInfo() { English = wxPorting.T("&Reverse+Assign"), Other = wxPorting.T("Invie&rte+Asigna") },
 	null
 };
  }
}