namespace Traincontroller2 {

  public static partial class Globals {
    public static LocalizeInfo[] italiano = new LocalizeInfo[] {
 	new LocalizeInfo() { English = wxPorting.T("Arrival"), Other = wxPorting.T("Arrivo") },
 	new LocalizeInfo() { English = wxPorting.T("From"), Other = wxPorting.T("Da") },
 	new LocalizeInfo() { English = wxPorting.T("To"), Other = wxPorting.T("Per") },
 	new LocalizeInfo() { English = wxPorting.T("Train"), Other = wxPorting.T("Treno") },
 	new LocalizeInfo() { English = wxPorting.T("Speed"), Other = wxPorting.T("Velocita'") },
 	new LocalizeInfo() { English = wxPorting.T("Min.Del."), Other = wxPorting.T("Rit.Ingr.") },
 	new LocalizeInfo() { English = wxPorting.T("Min.Late"), Other = wxPorting.T("Ritardo") },
 	new LocalizeInfo() { English = wxPorting.T("Status"), Other = wxPorting.T("Stato") },
 
 	new LocalizeInfo() { English = wxPorting.T("Entry"), Other = wxPorting.T("Entrata") },
 	new LocalizeInfo() { English = wxPorting.T("Exit"), Other = wxPorting.T("Uscita") },
 	new LocalizeInfo() { English = wxPorting.T("Entry/exit"), Other = wxPorting.T("Ingr./Uscita") },
 	new LocalizeInfo() { English = wxPorting.T("Times"), Other = wxPorting.T("Tempi") },
 
 	new LocalizeInfo() { English = wxPorting.T("Performance Statistics"), Other = wxPorting.T("Statistica Prestazioni") },
 	new LocalizeInfo() { English = wxPorting.T("Save"), Other = wxPorting.T("Salva") },
 
 	new LocalizeInfo() { English = wxPorting.T("Departing trains"), Other = wxPorting.T("Treni in partenza") },
 	new LocalizeInfo() { English = wxPorting.T("Train Schedule"), Other = wxPorting.T("Orario dei treni") },
 
 	new LocalizeInfo() { English = wxPorting.T("Close"), Other = wxPorting.T("Chiudi") },
 	new LocalizeInfo() { English = wxPorting.T("Stats"), Other = wxPorting.T("Statist.") },
 	new LocalizeInfo() { English = wxPorting.T("Print..."), Other = wxPorting.T("Stampa...") },
 	new LocalizeInfo() { English = wxPorting.T("Assign"), Other = wxPorting.T("Assegna") },
 	new LocalizeInfo() { English = wxPorting.T("Shunt"), Other = wxPorting.T("Manovra") },
 	new LocalizeInfo() { English = wxPorting.T("Cancel"), Other = wxPorting.T("Cancella") },
 	new LocalizeInfo() { English = wxPorting.T("Properties"), Other = wxPorting.T("Proprieta'") },
 	new LocalizeInfo() { English = wxPorting.T("Hide/Show titles"), Other = wxPorting.T("Mostra/Nascondi titoli") },
 
 	new LocalizeInfo() { English = wxPorting.T("Name"), Other = wxPorting.T("Nome") },
 	new LocalizeInfo() { English = wxPorting.T("Sections"), Other = wxPorting.T("Sezioni") },
 
 	new LocalizeInfo() { English = wxPorting.T("Track properties"), Other = wxPorting.T("Proprieta' del tratto di binario") },
 	new LocalizeInfo() { English = wxPorting.T("Track %d,%d"), Other = wxPorting.T("Binario %d,%d") },
 	new LocalizeInfo() { English = wxPorting.T("Length :"), Other = wxPorting.T("Lunghezza ") },
 	new LocalizeInfo() { English = wxPorting.T("Speed :"), Other = wxPorting.T("Velocita'") },
 	new LocalizeInfo() { English = wxPorting.T("Station :"), Other = wxPorting.T("Stazione") },
 	new LocalizeInfo() { English = wxPorting.T("Linked to west :"), Other = wxPorting.T("Collegato a ovest :") },
 	new LocalizeInfo() { English = wxPorting.T("Controls :"), Other = wxPorting.T("Controlla") },
 	new LocalizeInfo() { English = wxPorting.T("Linked to east :"), Other = wxPorting.T("Collegato a est :") },
 
 	new LocalizeInfo() { English = wxPorting.T("Trigger"), Other = wxPorting.T("Pedale") },
 	new LocalizeInfo() { English = wxPorting.T("Trigger properties"), Other = wxPorting.T("Proprieta' pedale") },
 	new LocalizeInfo() { English = wxPorting.T("Trigger at  %d,%d"), Other = wxPorting.T("Pedale a  %d,%d") },
 	new LocalizeInfo() { English = wxPorting.T("Action :"), Other = wxPorting.T("Azione :") },
 	new LocalizeInfo() { English = wxPorting.T("'@' in action = name of triggering train"), Other = wxPorting.T("'@' nell'azione = nome treno attivante") },
 	new LocalizeInfo() { English = wxPorting.T("Linked to track at coord:"), Other = wxPorting.T("Collegato al binario :") },
 	new LocalizeInfo() { English = wxPorting.T("Probabilities for action :"), Other = wxPorting.T("Probabilita' di azionamento :") },
 
 	new LocalizeInfo() { English = wxPorting.T("Signal properties"), Other = wxPorting.T("Proprieta' del segnale") },
 	new LocalizeInfo() { English = wxPorting.T("Signal at %d,%d"), Other = wxPorting.T("Segnale a %d,%d") },
 	new LocalizeInfo() { English = wxPorting.T("Signal Name :"), Other = wxPorting.T("Nome segnale") },
 	new LocalizeInfo() { English = wxPorting.T("Signal is always red"), Other = wxPorting.T("Segnale sempre rosso") },
 	new LocalizeInfo() { English = wxPorting.T("Signal has square frame"), Other = wxPorting.T("Segnale a vela quadra") },
 	new LocalizeInfo() { English = wxPorting.T("No penalty for train stopping at this signal"), Other = wxPorting.T("Nessuna penalita' per treni fermi a questo segnale") },
 	new LocalizeInfo() { English = wxPorting.T("Hidden"), Other = wxPorting.T("Invisibile") },
 	new LocalizeInfo() { English = wxPorting.T("Script file :"), Other = wxPorting.T("File script :") },
 
 	new LocalizeInfo() { English = wxPorting.T("Select Itinerary"), Other = wxPorting.T("Scelta Itinerario") },
 	new LocalizeInfo() { English = wxPorting.T("Select itinerary"), Other = wxPorting.T("Scelta itinerario") },
 	new LocalizeInfo() { English = wxPorting.T("Start Signal"), Other = wxPorting.T("Segnale di Inizio") },
 	new LocalizeInfo() { English = wxPorting.T("End Signal"), Other = wxPorting.T("Segnale di Fine") },
 	new LocalizeInfo() { English = wxPorting.T("Next Itinerary"), Other = wxPorting.T("Prossimo Itinerario") },
 	new LocalizeInfo() { English = wxPorting.T("&Select"), Other = wxPorting.T("&Scegli") },
 	new LocalizeInfo() { English = wxPorting.T("&Clear"), Other = wxPorting.T("&Annulla") },
 	new LocalizeInfo() { English = wxPorting.T("Cl&ose"), Other = wxPorting.T("&Chiudi") },
 
 	new LocalizeInfo() { English = wxPorting.T("Territory Information"), Other = wxPorting.T("Informazioni sul territorio") },
 	new LocalizeInfo() { English = wxPorting.T("Update"), Other = wxPorting.T("Aggiorna") },
 	new LocalizeInfo() { English = wxPorting.T("Print"), Other = wxPorting.T("Stampa") },
 
 	new LocalizeInfo() { English = wxPorting.T("Schedule"), Other = wxPorting.T("Orario") },
 	new LocalizeInfo() { English = wxPorting.T("Alerts"), Other = wxPorting.T("Eventi") },
 	new LocalizeInfo() { English = wxPorting.T("Train Info"), Other = wxPorting.T("Dettagli Treno") },
 
 	new LocalizeInfo() { English = wxPorting.T("Day Selection"), Other = wxPorting.T("Selezione Giorno") },
 	new LocalizeInfo() { English = wxPorting.T("Not all trains run every day of the week.nWhich day do you want to simulate?"), Other = wxPorting.T("Non tutti i treni circolano ogningiorno della settimana. Quale giorno vuoi simulare?") },
 	new LocalizeInfo() { English = wxPorting.T("Monday"), Other = wxPorting.T("Lunedi'") },
 	new LocalizeInfo() { English = wxPorting.T("Tuesday"), Other = wxPorting.T("Martedi'") },
 	new LocalizeInfo() { English = wxPorting.T("Wednesday"), Other = wxPorting.T("Mercoledi'") },
 	new LocalizeInfo() { English = wxPorting.T("Thursday"), Other = wxPorting.T("Giovedi'") },
 	new LocalizeInfo() { English = wxPorting.T("Friday"), Other = wxPorting.T("Venerdi'") },
 	new LocalizeInfo() { English = wxPorting.T("Saturday"), Other = wxPorting.T("Sabato") },
 	new LocalizeInfo() { English = wxPorting.T("Sunday"), Other = wxPorting.T("Domenica") },
 
 	new LocalizeInfo() { English = wxPorting.T("Write default preferences to ini file?"), Other = wxPorting.T("Scrivo le preferenze nel file ini?") },
 	new LocalizeInfo() { English = wxPorting.T("Preferences"), Other = wxPorting.T("Preferenze") },
 	new LocalizeInfo() { English = wxPorting.T("Full status info"), Other = wxPorting.T("Informazioni di stato complete") },
 	new LocalizeInfo() { English = wxPorting.T("Status line at top of window"), Other = wxPorting.T("Linea di stato in alto") },
 	new LocalizeInfo() { English = wxPorting.T("Alert sound on"), Other = wxPorting.T("Suono di avviso") },
 	new LocalizeInfo() { English = wxPorting.T("Beep on train entering scenario"), Other = wxPorting.T("Suono su ingresso treno") },
 	new LocalizeInfo() { English = wxPorting.T("View speed limits"), Other = wxPorting.T("Mostra limiti velocita'") },
 	new LocalizeInfo() { English = wxPorting.T("Automatically link signals"), Other = wxPorting.T("Collega segnali automaticamente") },
 	new LocalizeInfo() { English = wxPorting.T("Show grid"), Other = wxPorting.T("Mostra griglia") },
 	new LocalizeInfo() { English = wxPorting.T("View long blocks"), Other = wxPorting.T("Mostra blocchi lunghi") },
 	new LocalizeInfo() { English = wxPorting.T("Show seconds on clock"), Other = wxPorting.T("Mostra secondi sull'orologio") },
 	new LocalizeInfo() { English = wxPorting.T("Italian signals"), Other = wxPorting.T("Segnali italiani") },
 	new LocalizeInfo() { English = wxPorting.T("Hard performance tracking"), Other = wxPorting.T("Controllo stretto prestazioni") },
 	new LocalizeInfo() { English = wxPorting.T("Save preferences on exit"), Other = wxPorting.T("Salva preferenze in uscita") },
 
 	new LocalizeInfo() { English = wxPorting.T("Itinerary"), Other = wxPorting.T("Itinerari") },
 	new LocalizeInfo() { English = wxPorting.T("Name :"), Other = wxPorting.T("Nome :") },
 	new LocalizeInfo() { English = wxPorting.T("From signal '%s'"), Other = wxPorting.T("Dal segnale '%s'") },
 	new LocalizeInfo() { English = wxPorting.T("Next itinerary :"), Other = wxPorting.T("Prossimo itinerario") },
 
 	new LocalizeInfo() { English = wxPorting.T("Performance status"), Other = wxPorting.T("Sommario prestazione") },
 	new LocalizeInfo() { English = wxPorting.T("Wrong destinations :"), Other = wxPorting.T("Destinazioni sbagliate :") },
 	new LocalizeInfo() { English = wxPorting.T("Late trains :"), Other = wxPorting.T("Treni in ritardo :") },
 	new LocalizeInfo() { English = wxPorting.T("Thrown switches :"), Other = wxPorting.T("Scambi girati inutilmente :") },
 	new LocalizeInfo() { English = wxPorting.T("Cleared signals :"), Other = wxPorting.T("Segnali aperti inutilmente :") },
 	new LocalizeInfo() { English = wxPorting.T("Turned trains :"), Other = wxPorting.T("Inversioni di direzione inutili :") },
 	new LocalizeInfo() { English = wxPorting.T("Trains stopped at sig.:"), Other = wxPorting.T("Treni fermati a segnali :") },
 	new LocalizeInfo() { English = wxPorting.T("Wrong platforms :"), Other = wxPorting.T("Binari arrivi sbagliati :") },
 	new LocalizeInfo() { English = wxPorting.T("Commands denied :"), Other = wxPorting.T("Ordini sbagliati :") },
 	new LocalizeInfo() { English = wxPorting.T("Wrong stock assignments :"), Other = wxPorting.T("Assegnazioni materiali sbagliate :") },
 
 	new LocalizeInfo() { English = wxPorting.T("Created by"), Other = wxPorting.T("Creato da") },
 	new LocalizeInfo() { English = wxPorting.T("This is a game, and is not intended tonbe used to actually control train traffic."), Other = wxPorting.T("Questo e' un gioco e non e' progettato pernessere usato per il controllo reale del traffico ferroviario.") },
 	new LocalizeInfo() { English = wxPorting.T("This is free software, released under thenGNU General Public License."), Other = wxPorting.T(" Questo software e' gratis, distribuito sotto lanGNU General Public License.") },
 	new LocalizeInfo() { English = wxPorting.T("This is free software, released under thenGNU General Public License.nThe author declines any responsibility for any damagenthat might occur from the use of this program."), Other = wxPorting.T(" Questo software e' gratis, distribuito sotto lanGNU General Public License.nL'autore declina ogni responsabilita' per eventualindanni causati dall'uso di questo programma.") },
 	new LocalizeInfo() { English = wxPorting.T("This is free software, released under thenGNU General Public License Version 2.nThe author declines any responsibility for any damagenthat might occur from the use of this program."), Other = wxPorting.T(" Questo software e' gratis, distribuito sotto lanGNU General Public License.nL'autore declina ogni responsabilita' per eventualindanni causati dall'uso di questo programma.") },
 
 	new LocalizeInfo() { English = wxPorting.T("Layout Errors"), Other = wxPorting.T("Errori nel tracciato") },
 	new LocalizeInfo() { English = wxPorting.T("These trains will be delayed on entry:"), Other = wxPorting.T("Questi treni saranno ritardati in ingresso:") },
 	new LocalizeInfo() { English = wxPorting.T("%s and %s both enter at %s on %s"), Other = wxPorting.T("Sia %s che %s entrano a %s alle %s") },
 	new LocalizeInfo() { English = wxPorting.T("These trains have unknown entry or exit points:"), Other = wxPorting.T("Questi treni non hanno un punto di ingresso o uscita conosciuto") },
 	new LocalizeInfo() { English = wxPorting.T("%s enters from '%s', exits at '%s'"), Other = wxPorting.T("'%s' entra da '%s', esce a '%s'") },
 
 	new LocalizeInfo() { English = wxPorting.T("Some train has unknown entry/exit point!"), Other = wxPorting.T("Qualche treno ha un punto di ingresso/uscita sconosciuto!") },
 	new LocalizeInfo() { English = wxPorting.T("at"), Other = wxPorting.T("a") },
 
 
 	new LocalizeInfo() { English = wxPorting.T("Start"), Other = wxPorting.T("Partenza") },
 	new LocalizeInfo() { English = wxPorting.T("Fast"), Other = wxPorting.T("Veloce") },
 	new LocalizeInfo() { English = wxPorting.T("Slow"), Other = wxPorting.T("Lento") },
 	new LocalizeInfo() { English = wxPorting.T("Sched."), Other = wxPorting.T("Orario") },
 
 	new LocalizeInfo() { English = wxPorting.T("Simulation results"), Other = wxPorting.T("Risultati della simulazione") },
 	new LocalizeInfo() { English = wxPorting.T("Time"), Other = wxPorting.T("Tempo") },
 	new LocalizeInfo() { English = wxPorting.T("Total points"), Other = wxPorting.T("Punteggio totale") },
 	new LocalizeInfo() { English = wxPorting.T("Total min. of delayed entry"), Other = wxPorting.T("Minuti totali di ingressi ritardati") },
 	new LocalizeInfo() { English = wxPorting.T("Total min. trains arrived late"), Other = wxPorting.T("Minuti totali di treni arrivati in ritardo") },
 	new LocalizeInfo() { English = wxPorting.T("Total performance penalties"), Other = wxPorting.T("Penalita' totali") },
 	new LocalizeInfo() { English = wxPorting.T("Wrong destinatios"), Other = wxPorting.T("Destinazioni sbagliate") },
 	new LocalizeInfo() { English = wxPorting.T("Late trains"), Other = wxPorting.T("Treni in ritardo") },
 	new LocalizeInfo() { English = wxPorting.T("Wrong platforms"), Other = wxPorting.T("Binari di arrivo sbagliati") },
 	new LocalizeInfo() { English = wxPorting.T("Commands denied"), Other = wxPorting.T("Ordini sbagliati") },
 	new LocalizeInfo() { English = wxPorting.T("Trains waiting at signals"), Other = wxPorting.T("Treni fermati a segnali") },
 	new LocalizeInfo() { English = wxPorting.T("Thrown switches"), Other = wxPorting.T("Scambi girati inutilmente") },
 	new LocalizeInfo() { English = wxPorting.T("Cleared signals"), Other = wxPorting.T("Segnali aperti inutilmente") },
 	new LocalizeInfo() { English = wxPorting.T("Wrong stock assignments"), Other = wxPorting.T("Assegnazioni materiali sbagliate") },
 	new LocalizeInfo() { English = wxPorting.T("Reversed trains"), Other = wxPorting.T("Inversione di direzione inutili") },
 	new LocalizeInfo() { English = wxPorting.T("Save as text"), Other = wxPorting.T("Salva come file testo") },
 	new LocalizeInfo() { English = wxPorting.T("(hide canceled trains)"), Other = wxPorting.T("(nascondi treni non circolanti)") },
 	new LocalizeInfo() { English = wxPorting.T("(show canceled trains)"), Other = wxPorting.T("(mostra treni non circolanti)") },
 
 	new LocalizeInfo() { English = wxPorting.T("Enters"), Other = wxPorting.T("Ingresso") },
 	new LocalizeInfo() { English = wxPorting.T("At"), Other = wxPorting.T("Alle") },
 	new LocalizeInfo() { English = wxPorting.T("Exits"), Other = wxPorting.T("Uscita") },
 	new LocalizeInfo() { English = wxPorting.T("Before"), Other = wxPorting.T("per le") },
 	new LocalizeInfo() { English = wxPorting.T("Delay"), Other = wxPorting.T("Ingr.ritardato") },
 	new LocalizeInfo() { English = wxPorting.T("Late"), Other = wxPorting.T("Ritardo") },
 	new LocalizeInfo() { English = wxPorting.T("Status"), Other = wxPorting.T("Stato") },
 
 	new LocalizeInfo() { English = wxPorting.T("Station"), Other = wxPorting.T("Stazione") },
 	new LocalizeInfo() { English = wxPorting.T("Arrival"), Other = wxPorting.T("Arrivo") },
 	new LocalizeInfo() { English = wxPorting.T("Departure"), Other = wxPorting.T("Partenza") },
 	new LocalizeInfo() { English = wxPorting.T("Min.stop"), Other = wxPorting.T("Minuti di stop") },
 	new LocalizeInfo() { English = wxPorting.T("Plat."), Other = wxPorting.T("Binario") },
 	new LocalizeInfo() { English = wxPorting.T("Runs on"), Other = wxPorting.T("Circola i") },
 	new LocalizeInfo() { English = wxPorting.T("Notes"), Other = wxPorting.T("Note") },
 	new LocalizeInfo() { English = wxPorting.T("To&nbsp;&nbsp;"), Other = wxPorting.T("Per&nbsp;&nbsp;") },
 	new LocalizeInfo() { English = wxPorting.T("To&nbsp;&nbsp;&nbsp;"), Other = wxPorting.T("Per&nbsp;&nbsp;&nbsp;") },
 	new LocalizeInfo() { English = wxPorting.T("Runs on&nbsp;&nbsp;"), Other = wxPorting.T("Circola i&nbsp;") },
 	new LocalizeInfo() { English = wxPorting.T("Runs&nbsp;on&nbsp;&nbsp;"), Other = wxPorting.T("Circola&nbsp;i&nbsp;") },
 	new LocalizeInfo() { English = wxPorting.T("Minimum stop (sec)"), Other = wxPorting.T("Attesa minima (sec)") },
 
 	new LocalizeInfo() { English = wxPorting.T("Territory"), Other = wxPorting.T("Territorio") },
 
 	new LocalizeInfo() { English = wxPorting.T("Are you sure you want to restorenthe simulation to its saved state?"), Other = wxPorting.T("Ripartire dall'ora iniziale del salvataggio?") },
 	new LocalizeInfo() { English = wxPorting.T("This will delete the current layout.nAre you sure you want to continue?"), Other = wxPorting.T("Quest'azione cancella il tracciato.nSei sicuro di voler continuare?") },
 	new LocalizeInfo() { English = wxPorting.T("Replay interrupted."), Other = wxPorting.T("Replay interrotto.") },
 
 
 	new LocalizeInfo() { English = wxPorting.T("/File/Open recent"), Other = wxPorting.T("/File/Apri recenti") },
 
 	new LocalizeInfo() { English = wxPorting.T("Train %s waiting at %d,%d!"), Other = wxPorting.T("Treno %s fermo a %d,%d!") },
 	new LocalizeInfo() { English = wxPorting.T("Train %s waiting at"), Other = wxPorting.T("Treno %s fermo a") },
 	new LocalizeInfo() { English = wxPorting.T("You must assign train %s using stock from train %s!"), Other = wxPorting.T("Devi assegnare il treno %s usando il materiale dal treno %s!") },
 	new LocalizeInfo() { English = wxPorting.T("Train %s derailed at %s!"), Other = wxPorting.T("Treno %s deragliato a %s!") },
 	new LocalizeInfo() { English = wxPorting.T("Train %s derailed at %d,%d!"), Other = wxPorting.T("Treno %s deragliato a %d,%d!") },
 	new LocalizeInfo() { English = wxPorting.T("Train %s derailed!"), Other = wxPorting.T("Treno %s deragliato") },
 	new LocalizeInfo() { English = wxPorting.T("Train %s delayed at %s!"), Other = wxPorting.T("Treno %s in ritardo a %s!") },
 	new LocalizeInfo() { English = wxPorting.T("Cannot reverse direction. Path is busy."), Other = wxPorting.T("Impossibile invertire la direzione. Binario occupato.") },
 	new LocalizeInfo() { English = wxPorting.T("This signal cannot be turned to green!"), Other = wxPorting.T("Impossibile porre questo segnale a verde!") },
 	new LocalizeInfo() { English = wxPorting.T("You must wait for train to stop."), Other = wxPorting.T("Devi attendere che il treno sia fermo.") },
 	new LocalizeInfo() { English = wxPorting.T("Reverse train direction?"), Other = wxPorting.T("Invertire la direzione del treno?") },
 	new LocalizeInfo() { English = wxPorting.T("Proceed to next station?"), Other = wxPorting.T("Avanzare il treno fino alla prossima stazione?") },
 
 	new LocalizeInfo() { English = wxPorting.T("Sorry, this feature is not available on this scenario."), Other = wxPorting.T("Spiacente, ma questa funzione non e' disponibile in questo scenario.") },
 	new LocalizeInfo() { English = wxPorting.T("No station has distance information."), Other = wxPorting.T("Nessuna stazione ha informazioni sulle progressive chilometriche.") },
 	new LocalizeInfo() { English = wxPorting.T("Train Schedule Graph"), Other = wxPorting.T("Grafico Orario") },
 
 	new LocalizeInfo() { English = wxPorting.T("Error reading"), Other = wxPorting.T("Errore nella lettura di") },
 	new LocalizeInfo() { English = wxPorting.T("Final stop"), Other = wxPorting.T("Ultima fermata") },
 	new LocalizeInfo() { English = wxPorting.T("at"), Other = wxPorting.T("alle") },
 	new LocalizeInfo() { English = wxPorting.T("Next stop"), Other = wxPorting.T("Prossima fermata") },
 	new LocalizeInfo() { English = wxPorting.T("ready"), Other = wxPorting.T("pronto") },
 	new LocalizeInfo() { English = wxPorting.T("Canceled - runs on"), Other = wxPorting.T("Soppresso - circola il") },
 	new LocalizeInfo() { English = wxPorting.T("Shunting"), Other = wxPorting.T("Manovra") },
 	new LocalizeInfo() { English = wxPorting.T("to"), Other = wxPorting.T("per") },
 	new LocalizeInfo() { English = wxPorting.T("Running. Dest."), Other = wxPorting.T("In movimento. Dest.") },
 	new LocalizeInfo() { English = wxPorting.T("Stopped. ETD"), Other = wxPorting.T("Fermo. Parte alle") },
 	new LocalizeInfo() { English = wxPorting.T("Dest."), Other = wxPorting.T("Dest.") },
 	new LocalizeInfo() { English = wxPorting.T("Delayed entry at"), Other = wxPorting.T("Ingresso ritardato a") },
 	new LocalizeInfo() { English = wxPorting.T("Starting"), Other = wxPorting.T("In avvio") },
 	new LocalizeInfo() { English = wxPorting.T("Waiting"), Other = wxPorting.T("In attesa") },
 	new LocalizeInfo() { English = wxPorting.T("derailed"), Other = wxPorting.T("deragliato") },
 	new LocalizeInfo() { English = wxPorting.T("Arrived at"), Other = wxPorting.T("Arrivato a") },
 	new LocalizeInfo() { English = wxPorting.T("instead of"), Other = wxPorting.T("invece che a") },
 	new LocalizeInfo() { English = wxPorting.T("Arrived"), Other = wxPorting.T("Arrivato con") },
 	new LocalizeInfo() { English = wxPorting.T("min. late at"), Other = wxPorting.T("min. di ritardo a") },
 	new LocalizeInfo() { English = wxPorting.T("Arrived on time"), Other = wxPorting.T("Arrivato in orario") },
 	new LocalizeInfo() { English = wxPorting.T("stock for"), Other = wxPorting.T("materiale per") },
 
 	new LocalizeInfo() { English = wxPorting.T("Signal at"), Other = wxPorting.T("Segnale a") },
 	new LocalizeInfo() { English = wxPorting.T("not linked to any track"), Other = wxPorting.T("non collegato ad alcun binario") },
 	new LocalizeInfo() { English = wxPorting.T("Track at"), Other = wxPorting.T("Binario a") },
 	new LocalizeInfo() { English = wxPorting.T("not controlled by signal at"), Other = wxPorting.T("non controllato dal segnale a") },
 	new LocalizeInfo() { English = wxPorting.T("linked to non-existant track at"), Other = wxPorting.T("collegato a binario inesistente a") },
 	new LocalizeInfo() { English = wxPorting.T("not linked back to"), Other = wxPorting.T("non ricollegato al binario a") },
 	new LocalizeInfo() { English = wxPorting.T("Switch at"), Other = wxPorting.T("Scambio a") },
 	new LocalizeInfo() { English = wxPorting.T("linked to non-existant switch at"), Other = wxPorting.T("collegato a scambio inesistente a") },
 	new LocalizeInfo() { English = wxPorting.T("not linked back to switch at"), Other = wxPorting.T("non ricollegato allo scambio a") },
 	new LocalizeInfo() { English = wxPorting.T("Checking for errors in layout...n"), Other = wxPorting.T("Controllo errorin nel tracciato...n") },
 	new LocalizeInfo() { English = wxPorting.T("nly like tracks can be linked."), Other = wxPorting.T("Solo binari compatibili possono essere collegati.") },
 	new LocalizeInfo() { English = wxPorting.T("Only horizontal or vertical tracks can be linked automatically.nTo link other track types, use the track properties dialog."), Other = wxPorting.T("Solo binari orizzontali o verticali possono essere collegati automaticamente. Per collegare altri tipo di binario, usare il dialogo delle proprieta'.") },
 	new LocalizeInfo() { English = wxPorting.T("Signals can only be linked to a track."), Other = wxPorting.T("Un segnale puo' solo essere collegato a un binario.") },
 	new LocalizeInfo() { English = wxPorting.T("Triggers can only be linked to a track."), Other = wxPorting.T("Un pedale puo' solo essere collegato a un binario.") },
 	new LocalizeInfo() { English = wxPorting.T("Entry/Exit point can only be linked to a track."), Other = wxPorting.T("Un punto di ingresso/uscita puo' solo essere collegato a un binario.") },
 
 	new LocalizeInfo() { English = wxPorting.T("speed"), Other = wxPorting.T("veloc.") },
 	new LocalizeInfo() { English = wxPorting.T("length"), Other = wxPorting.T("lungh.") },
 	new LocalizeInfo() { English = wxPorting.T("Station"), Other = wxPorting.T("Stazione") },
 	new LocalizeInfo() { English = wxPorting.T("entry/exit"), Other = wxPorting.T("ingresso/uscita") },
 	new LocalizeInfo() { English = wxPorting.T("Signal"), Other = wxPorting.T("Segnale") },
 	new LocalizeInfo() { English = wxPorting.T("controls"), Other = wxPorting.T("controlla") },
 
 	new LocalizeInfo() { English = wxPorting.T("Station of"), Other = wxPorting.T("Stazione di") },
 	new LocalizeInfo() { English = wxPorting.T("Platform"), Other = wxPorting.T("Binario") },
 	new LocalizeInfo() { English = wxPorting.T("An itinerary by the same name already exists.nDo you want to replace the old itinerary with the new one?"), Other = wxPorting.T("Un itinerarion con lo stesso nome esiste gia'.nLo vuoi rimpiazzare con quello nuovo?") },
 
 	new LocalizeInfo() { English = wxPorting.T("Cannot create log file."), Other = wxPorting.T("Impossibile create il file di log.") },
 	new LocalizeInfo() { English = wxPorting.T("Cannot read log file."), Other = wxPorting.T("Impossibile leggere il file di log.") },
 	new LocalizeInfo() { English = wxPorting.T("Do you want to restart the simulation?"), Other = wxPorting.T("Vuoi far ripartire la simulazione dall'inizio?") },
 	new LocalizeInfo() { English = wxPorting.T("Simulation restarted."), Other = wxPorting.T("Simulazione ritornata alle condizioni iniziali.") },
 
 	new LocalizeInfo() { English = wxPorting.T("Stop"), Other = wxPorting.T("Stop") },
 	new LocalizeInfo() { English = wxPorting.T("Start"), Other = wxPorting.T("Parti") },
 	new LocalizeInfo() { English = wxPorting.T("Restart"), Other = wxPorting.T("Riparti") },
 	new LocalizeInfo() { English = wxPorting.T("Layout saved in file"), Other = wxPorting.T("Tracciato salvato nel file") },
 	new LocalizeInfo() { English = wxPorting.T("Game status saved in file"), Other = wxPorting.T("Stato del gioco salvato nel file") },
 	new LocalizeInfo() { English = wxPorting.T("No schedule for this territory!"), Other = wxPorting.T("Orario inesistente per questo tracciato!") },
 	new LocalizeInfo() { English = wxPorting.T("Question"), Other = wxPorting.T("Domanda") },
 	new LocalizeInfo() { English = wxPorting.T("Warning"), Other = wxPorting.T("Attenzione") },
 	new LocalizeInfo() { English = wxPorting.T("Attention"), Other = wxPorting.T("Errore") },
 	new LocalizeInfo() { English = wxPorting.T("Open File"), Other = wxPorting.T("Apri file") },
 	new LocalizeInfo() { English = wxPorting.T("Error"), Other = wxPorting.T("Errore") },
 	new LocalizeInfo() { English = wxPorting.T("Scenarios"), Other = wxPorting.T("Scenari") },
 	new LocalizeInfo() { English = wxPorting.T("Saved games"), Other = wxPorting.T("Partite salvate") },
 	new LocalizeInfo() { English = wxPorting.T("All files (*.*)"), Other = wxPorting.T("Tutti i files (*.*)") },
 	new LocalizeInfo() { English = wxPorting.T("Icons"), Other = wxPorting.T("Icone") },
 	new LocalizeInfo() { English = wxPorting.T("Save File"), Other = wxPorting.T("Salva File") },
 	new LocalizeInfo() { English = wxPorting.T("Can't create file"), Other = wxPorting.T("Impossibile creare il file") },
         new LocalizeInfo() { English = wxPorting.T("Platform Graph"), Other = wxPorting.T("Grafico Binari") },
         new LocalizeInfo() { English = wxPorting.T("&Platform Graph"), Other = wxPorting.T("Grafico &Binari") },
         new LocalizeInfo() { English = wxPorting.T("Show platforms occupancy over time."), Other = wxPorting.T("Mostra l'occupazione dei binari durante la giornata.") },
 
 	new LocalizeInfo() { English = wxPorting.T("/_File"), Other = wxPorting.T("/_File") },
 	new LocalizeInfo() { English = wxPorting.T("/File/_Open"), Other = wxPorting.T("/File/_Apri") },
 	new LocalizeInfo() { English = wxPorting.T("/File/Open re_cent"), Other = wxPorting.T("/File/Apri re_cente") },
 	new LocalizeInfo() { English = wxPorting.T("/File/_Save Game"), Other = wxPorting.T("/File/_Salva Gioco") },
 	new LocalizeInfo() { English = wxPorting.T("/File/_Restore"), Other = wxPorting.T("/File/_Recupera") },
 	new LocalizeInfo() { English = wxPorting.T("/File/Save _As"), Other = wxPorting.T("/File/Salva _Come") },
 	new LocalizeInfo() { English = wxPorting.T("/File/_Log"), Other = wxPorting.T("/File/Re_gistra") },
 	new LocalizeInfo() { English = wxPorting.T("/File/_Replay"), Other = wxPorting.T("/File/_Replay") },
 	new LocalizeInfo() { English = wxPorting.T("/File/About..."), Other = wxPorting.T("/File/Informazioni...") },
 	new LocalizeInfo() { English = wxPorting.T("/File/Quit"), Other = wxPorting.T("/File/Uscita") },
 	new LocalizeInfo() { English = wxPorting.T("/Edit/_Edit"), Other = wxPorting.T("/Edit/_Edit") },
 	new LocalizeInfo() { English = wxPorting.T("/Edit/_New Train"), Other = wxPorting.T("/Edit/_Nuovo Treno") },
 	new LocalizeInfo() { English = wxPorting.T("/Edit/Itinerary"), Other = wxPorting.T("/Edit/Itinerario") },
 	new LocalizeInfo() { English = wxPorting.T("/Edit/_Save Layout"), Other = wxPorting.T("/Edit/_Salva Tracciato") },
 	new LocalizeInfo() { English = wxPorting.T("/Edit/_Preferences"), Other = wxPorting.T("/Edit/_Preferenze") },
 	new LocalizeInfo() { English = wxPorting.T("/Edit/_New"), Other = wxPorting.T("/Edit/_Nuovo Tracciato") },
 	new LocalizeInfo() { English = wxPorting.T("/Edit/_Info"), Other = wxPorting.T("/Edit/_Informazioni") },
 	new LocalizeInfo() { English = wxPorting.T("/_Run"), Other = wxPorting.T("/_Simula") },
 	new LocalizeInfo() { English = wxPorting.T("/Run/_Start"), Other = wxPorting.T("/Simula/_Parti") },
 	new LocalizeInfo() { English = wxPorting.T("/Run/View _Graph"), Other = wxPorting.T("/Simula/Orario _Grafico") },
 	new LocalizeInfo() { English = wxPorting.T("/Run/Restart"), Other = wxPorting.T("/Simula/Riparti") },
 	new LocalizeInfo() { English = wxPorting.T("/Run/_Fast"), Other = wxPorting.T("/Simula/_Veloce") },
 	new LocalizeInfo() { English = wxPorting.T("/Run/S_low"), Other = wxPorting.T("/Simula/_Lento") },
 	new LocalizeInfo() { English = wxPorting.T("/Run/S_tation schedule"), Other = wxPorting.T("/Simula/Orario di _Stazione") },
 	new LocalizeInfo() { English = wxPorting.T("/Run/Set sig. to green"), Other = wxPorting.T("/Simula/Segnali autom. a verde") },
 	new LocalizeInfo() { English = wxPorting.T("/Run/Performance"), Other = wxPorting.T("/Simula/Prestazioni") },
 
 	new LocalizeInfo() { English = wxPorting.T("# about dialog") },
 
 	new LocalizeInfo() { English = wxPorting.T("This is a game, and is not intended tonbe used to actually control train traffic."), Other = wxPorting.T("Questo programma e' un gioco, e non e' statonprogettato per il controllo del traffico ferroviario reale.") },
 	new LocalizeInfo() { English = wxPorting.T("This is free software, released under thenGNU General Public License 2."), Other = wxPorting.T("Questo software e' gratis,ndistribuito sotto la GNU General Public License 2.") },
 	new LocalizeInfo() { English = wxPorting.T("The author declines any responsibility for any damagenthat might occur from the use of this program."), Other = wxPorting.T("wxPorting.L'autore declina ogni responsabilita' per eventualindanni causati dall'uso di questo programma.") },
 
 	new LocalizeInfo() { English = wxPorting.T("Assign rolling stock"), Other = wxPorting.T("Assegnazione materiale rotabile") },
 	new LocalizeInfo() { English = wxPorting.T("&Assign"), Other = wxPorting.T("&Assegna") },
 	new LocalizeInfo() { English = wxPorting.T("S&hunt"), Other = wxPorting.T("&Manovra") },
 	new LocalizeInfo() { English = wxPorting.T("Sp&lit"), Other = wxPorting.T("Spe&zza") },
 	new LocalizeInfo() { English = wxPorting.T("&Properties"), Other = wxPorting.T("&Proprieta'") },
 	new LocalizeInfo() { English = wxPorting.T("&Cancel"), Other = wxPorting.T("&Cancella") },
 
 	new LocalizeInfo() { English = wxPorting.T("Itinerary definition"), Other = wxPorting.T("Definizione itinerari") },
 	new LocalizeInfo() { English = wxPorting.T("&Name"), Other = wxPorting.T("Nome") },
 	new LocalizeInfo() { English = wxPorting.T("From signal"), Other = wxPorting.T("Dal segnale") },
 	new LocalizeInfo() { English = wxPorting.T("Ne&xt itinerary"), Other = wxPorting.T("&Prossimo itinerario") },
 
 	new LocalizeInfo() { English = wxPorting.T("Performance"), Other = wxPorting.T("Prestazione") },
 	new LocalizeInfo() { English = wxPorting.T("Count"), Other = wxPorting.T("Frequenza") },
 	new LocalizeInfo() { English = wxPorting.T("Points"), Other = wxPorting.T("Penalita'") },
 	new LocalizeInfo() { English = wxPorting.T("Total"), Other = wxPorting.T("Totale") },
 	new LocalizeInfo() { English = wxPorting.T("Wrong destinations"), Other = wxPorting.T("Destinazioni sbagliate") },
 	new LocalizeInfo() { English = wxPorting.T("Late trains"), Other = wxPorting.T("Treni arrivati in ritardo") },
 	new LocalizeInfo() { English = wxPorting.T("Wrong platforms"), Other = wxPorting.T("Binari sbagliati") },
 	new LocalizeInfo() { English = wxPorting.T("Commands denied"), Other = wxPorting.T("Ordini sbagliati") },
 	new LocalizeInfo() { English = wxPorting.T("Trains stopped at signals"), Other = wxPorting.T("Treni fermati a segnali") },
 	new LocalizeInfo() { English = wxPorting.T("Turned trains"), Other = wxPorting.T("Inversioni di direzione inutili") },
 	new LocalizeInfo() { English = wxPorting.T("Thrown switches"), Other = wxPorting.T("Scambi girati inutilmente") },
 	new LocalizeInfo() { English = wxPorting.T("Cleared signals"), Other = wxPorting.T("Segnali messi a verde inutilmente") },
 	new LocalizeInfo() { English = wxPorting.T("Wrong stock assignments"), Other = wxPorting.T("Assegnazioni materiale sbagliate") },
 
 
 	new LocalizeInfo() { English = wxPorting.T("Preferences"), Other = wxPorting.T("Preferenze") },
         new LocalizeInfo() { English = wxPorting.T("Options"), Other = wxPorting.T("Opzioni") },
 	new LocalizeInfo() { English = wxPorting.T("Short train info"), Other = wxPorting.T("Informazioni treni ridotte") },
 	new LocalizeInfo() { English = wxPorting.T("Status line at top of window"), Other = wxPorting.T("Linea di stato in alto") },
 	new LocalizeInfo() { English = wxPorting.T("Alert sound on"), Other = wxPorting.T("Suono di avviso abilitato") },
 	new LocalizeInfo() { English = wxPorting.T("Alert on train entering layout"), Other = wxPorting.T("Avviso sonoro su ingresso treno nel tracciato") },
 	new LocalizeInfo() { English = wxPorting.T("View speed limits"), Other = wxPorting.T("Mostra i punti di cambio velocita'") },
 	new LocalizeInfo() { English = wxPorting.T("Automatically link signals"), Other = wxPorting.T("Collega automaticamente i segnali") },
         new LocalizeInfo() { English = wxPorting.T("Link signals to left track"), Other = wxPorting.T("Collega i segnali al binario alla loro sinistra") },
 	new LocalizeInfo() { English = wxPorting.T("Show grid"), Other = wxPorting.T("Mosta griglia") },
 	new LocalizeInfo() { English = wxPorting.T("View long blocks"), Other = wxPorting.T("Mostra i binari lunghi") },
 	new LocalizeInfo() { English = wxPorting.T("Show seconds on clock"), Other = wxPorting.T("Mostra i secondi sull'orologio") },
 	new LocalizeInfo() { English = wxPorting.T("Traditional signals"), Other = wxPorting.T("Segnali tradizionali") },
 	new LocalizeInfo() { English = wxPorting.T("Strong performance checking"), Other = wxPorting.T("Controllo piu' restrittivo sugli errori") },
 	new LocalizeInfo() { English = wxPorting.T("Show linked objects in editor"), Other = wxPorting.T("Mostra i collegamenti degli oggetti nell'editor") },
         new LocalizeInfo() { English = wxPorting.T("Show scripted objects in editor"), Other = wxPorting.T("Mostra gli oggetti con script nell'editor") },
 	new LocalizeInfo() { English = wxPorting.T("Show trains icons"), Other = wxPorting.T("Mostra le icone dei treni") },
 	new LocalizeInfo() { English = wxPorting.T("Show trains tooltip"), Other = wxPorting.T("Mostra il \"tooltip\" per i treni") },
         new LocalizeInfo() { English = wxPorting.T("Enable random delays"), Other = wxPorting.T("Abilita ritardi casuali") },
         new LocalizeInfo() { English = wxPorting.T("Wait while playing sounds"), Other = wxPorting.T("Blocca la simulazione durante i suoni") },
 	new LocalizeInfo() { English = wxPorting.T("Check the desired options:"), Other = wxPorting.T("Selezionare le opzioni desiderate:") },
 
         new LocalizeInfo() { English = wxPorting.T("Environment"), Other = wxPorting.T("Ambiente") },
         new LocalizeInfo() { English = wxPorting.T("Path to sound file for alert notifications"), Other = wxPorting.T("Percorso del file suono degli avvisi") },
         new LocalizeInfo() { English = wxPorting.T("Path to sound file for train entry"), Other = wxPorting.T("Percorso del file suono per l'ingresso treni") },
         new LocalizeInfo() { English = wxPorting.T("Directories with signal scripts"), Other = wxPorting.T("Directory con script segnali") },
 
         new LocalizeInfo() { English = wxPorting.T("Background"), Other = wxPorting.T("Sfondo") },
         new LocalizeInfo() { English = wxPorting.T("Free Track"), Other = wxPorting.T("Binario Libero") },
         new LocalizeInfo() { English = wxPorting.T("Reserved Track"), Other = wxPorting.T("Binario Riservato") },
         new LocalizeInfo() { English = wxPorting.T("Reserved for Shunting"), Other = wxPorting.T("Binario Riservato per Manovra") },
         new LocalizeInfo() { English = wxPorting.T("Occupied"), Other = wxPorting.T("Occupato") },
         new LocalizeInfo() { English = wxPorting.T("Reserved for Working"), Other = wxPorting.T("Riservato per Lavori") },
         new LocalizeInfo() { English = wxPorting.T("Switch Outline"), Other = wxPorting.T("Contorno Scambi") },
         new LocalizeInfo() { English = wxPorting.T("Text"), Other = wxPorting.T("Testo") },
         new LocalizeInfo() { English = wxPorting.T("Color..."), Other = wxPorting.T("Colore...") },
 
         new LocalizeInfo() { English = wxPorting.T("Enable HTTP server"), Other = wxPorting.T("Abilita il server HTTP") },
         new LocalizeInfo() { English = wxPorting.T("HTTP Server Port"), Other = wxPorting.T("Porta Server HTTP") },
         new LocalizeInfo() { English = wxPorting.T("User name"), Other = wxPorting.T("Nome utente") },
 
 	new LocalizeInfo() { English = wxPorting.T("Scenario Information"), Other = wxPorting.T("Informazioni Scenario") },
 
 	new LocalizeInfo() { English = wxPorting.T("Day selection"), Other = wxPorting.T("Selezione giorno") },
 	new LocalizeInfo() { English = wxPorting.T("&Continue"), Other = wxPorting.T("&Continua") },
 
 	new LocalizeInfo() { English = wxPorting.T("Signal at coordinates :"), Other = wxPorting.T("Segnale alle coordinate :") },
 	new LocalizeInfo() { English = wxPorting.T("Signal name :"), Other = wxPorting.T("Nome segnale") },
 	new LocalizeInfo() { English = wxPorting.T("Linked to east :"), Other = wxPorting.T("Linkato a est :") },
 	new LocalizeInfo() { English = wxPorting.T("Linked to west :"), Other = wxPorting.T("Linkato a ovest :") },
 	new LocalizeInfo() { English = wxPorting.T("Signal is always red"), Other = wxPorting.T("Segnale sempre al rosso") },
 	new LocalizeInfo() { English = wxPorting.T("Signal has square frame"), Other = wxPorting.T("Segnale a vela quadra") },
 	new LocalizeInfo() { English = wxPorting.T("No penalty for train stopping at this signal"), Other = wxPorting.T("Nessuna penalita' se un treno si ferma a questo segnale") },
 
 	new LocalizeInfo() { English = wxPorting.T("Station schedule"), Other = wxPorting.T("Orario di stazione") },
 	new LocalizeInfo() { English = wxPorting.T("S&tation scheduletF5"), Other = wxPorting.T("Orario di s&tazionetF5") },
 	new LocalizeInfo() { English = wxPorting.T("&Schedule for station :"), Other = wxPorting.T("&Orario per la stazione di :") },
 	new LocalizeInfo() { English = wxPorting.T("&Ignore platform number"), Other = wxPorting.T("&Ignora il binario di arrivo") },
 	new LocalizeInfo() { English = wxPorting.T("&Close"), Other = wxPorting.T("&Chiudi") },
 	new LocalizeInfo() { English = wxPorting.T("&Print"), Other = wxPorting.T("&Stampa") },
 
 	new LocalizeInfo() { English = wxPorting.T("Layout Information"), Other = wxPorting.T("Informazioni sul tracciato") },
 
 	new LocalizeInfo() { English = wxPorting.T("Track Properties"), Other = wxPorting.T("Proprieta' del binario") },
 	new LocalizeInfo() { English = wxPorting.T("Track Length (m) :"), Other = wxPorting.T("Lunghezza binario (m) :") },
 	new LocalizeInfo() { English = wxPorting.T("Station name :"), Other = wxPorting.T("Nome stazione :") },
 	new LocalizeInfo() { English = wxPorting.T("Switch name :"), Other = wxPorting.T("Nome scambio :") },
         new LocalizeInfo() { English = wxPorting.T("Speed(s) :"), Other = wxPorting.T("Velocita' :") },
         new LocalizeInfo() { English = wxPorting.T("Branch Speed(s) :"), Other = wxPorting.T("Velocita' in deviata :") },
 
 	new LocalizeInfo() { English = wxPorting.T("Train Properties"), Other = wxPorting.T("Proprieta' del treno") },
 	new LocalizeInfo() { English = wxPorting.T("Train name"), Other = wxPorting.T("Nome treno") },
 	new LocalizeInfo() { English = wxPorting.T("Train type"), Other = wxPorting.T("Tipo treno") },
 	new LocalizeInfo() { English = wxPorting.T("Entry point"), Other = wxPorting.T("Punto di ingresso") },
 	new LocalizeInfo() { English = wxPorting.T("Entry time (hh:mm)"), Other = wxPorting.T("Orario di ingresso (hh:mm)") },
 	new LocalizeInfo() { English = wxPorting.T("Exit point"), Other = wxPorting.T("Punto di uscita") },
 	new LocalizeInfo() { English = wxPorting.T("Exit time (hh:mm)"), Other = wxPorting.T("Orario di uscita (hh:mm)") },
 	new LocalizeInfo() { English = wxPorting.T("Wait arrival of train"), Other = wxPorting.T("Attende l'arrivo del treno") },
 	new LocalizeInfo() { English = wxPorting.T("Stock for train"), Other = wxPorting.T("Materiale per treno") },
 	new LocalizeInfo() { English = wxPorting.T("Runs on"), Other = wxPorting.T("Circola il") },
 	new LocalizeInfo() { English = wxPorting.T("Train length :"), Other = wxPorting.T("Lunghezza treno :") },
 
 	new LocalizeInfo() { English = wxPorting.T("Trigger Properties"), Other = wxPorting.T("Proprieta' Pedale") },
 	new LocalizeInfo() { English = wxPorting.T("Trigger at coordinates :"), Other = wxPorting.T("Pedale alle coordinate :") },
 	new LocalizeInfo() { English = wxPorting.T("Actionn(e.g. \"click 12,4\")"), Other = wxPorting.T("Azionen(es. \"click 12,4\")") },
 	new LocalizeInfo() { English = wxPorting.T("Linked to track at :"), Other = wxPorting.T("Collegato al binario a :") },
 	new LocalizeInfo() { English = wxPorting.T("Probabilities :"), Other = wxPorting.T("Probabilita'") },
 	new LocalizeInfo() { English = wxPorting.T("Action:             ('@' in action = name of triggering train)"), Other = wxPorting.T("Azione: ('@' nell'azione = nome del treno attivante)") },
 	new LocalizeInfo() { English = wxPorting.T("Linked to track at coord :"), Other = wxPorting.T("Collegato al binario alle coord. :") },
 	new LocalizeInfo() { English = wxPorting.T("Probabilities for action :"), Other = wxPorting.T("Probabilita' per l'azione :") },
 
 	new LocalizeInfo() { English = wxPorting.T("cannot load"), Other = wxPorting.T("Impossibile caricare") },
 	new LocalizeInfo() { English = wxPorting.T("Destination"), Other = wxPorting.T("Destinazione") },
 	new LocalizeInfo() { English = wxPorting.T("Assigning stock of train %s arrived at station %s"), Other = wxPorting.T("Assegnamento materiale treno %s arrivato a %s") },
 	new LocalizeInfo() { English = wxPorting.T("From signal '%s'"), Other = wxPorting.T("Dal segnale '%s'") },
 
 	new LocalizeInfo() { English = wxPorting.T("&File"), Other = wxPorting.T("&File") },
 	new LocalizeInfo() { English = wxPorting.T("&Open...tCtrl-O"), Other = wxPorting.T("&Apri...tCtrl-O") },
 	new LocalizeInfo() { English = wxPorting.T("&Save Game..."), Other = wxPorting.T("&Salva Gioco...") },
 	new LocalizeInfo() { English = wxPorting.T("&Restore..."), Other = wxPorting.T("&Riparti simulazione...") },
 	new LocalizeInfo() { English = wxPorting.T("Page set&up"), Other = wxPorting.T("Config&ura Pagina Stampa") },
 	new LocalizeInfo() { English = wxPorting.T("Pre&view"), Other = wxPorting.T("Bo&zza di Stampa") },
 	new LocalizeInfo() { English = wxPorting.T("&Print"), Other = wxPorting.T("Stam&pa") },
 	new LocalizeInfo() { English = wxPorting.T("&Edit"), Other = wxPorting.T("&Edit") },
 	new LocalizeInfo() { English = wxPorting.T("&Itinerary"), Other = wxPorting.T("&Itinerari") },
 	new LocalizeInfo() { English = wxPorting.T("&Save Layout"), Other = wxPorting.T("&Salva Tracciato") },
 	new LocalizeInfo() { English = wxPorting.T("&Preferences..."), Other = wxPorting.T("&Preferenze") },
 	new LocalizeInfo() { English = wxPorting.T("ExittAlt-F4"), Other = wxPorting.T("EscitAlt-F4") },
 	new LocalizeInfo() { English = wxPorting.T("Ne&w"), Other = wxPorting.T("&Nuovo Tracciato") },
 	new LocalizeInfo() { English = wxPorting.T("In&fo"), Other = wxPorting.T("&Informazioni") },
 	new LocalizeInfo() { English = wxPorting.T("&Run"), Other = wxPorting.T("&Simula") },
 	new LocalizeInfo() { English = wxPorting.T("&StarttCtrl-S"), Other = wxPorting.T("&PartitCtrl-S") },
 	new LocalizeInfo() { English = wxPorting.T("&GraphtCtrl-G"), Other = wxPorting.T("Orario &GraficotCtrl-G") },
 	new LocalizeInfo() { English = wxPorting.T("&Late GraphtCtrl-wxPorting.L"), Other = wxPorting.T("Grafico RitarditCtrl-wxPorting.L") },
 	new LocalizeInfo() { English = wxPorting.T("&Restart..."), Other = wxPorting.T("&Riparti...") },
 	new LocalizeInfo() { English = wxPorting.T("&FasttCtrl-X"), Other = wxPorting.T("&VelocetCtrl-X") },
 	new LocalizeInfo() { English = wxPorting.T("&SlowtCtrl-Z"), Other = wxPorting.T("&LentotCtrl-Z") },
 	new LocalizeInfo() { English = wxPorting.T("S&kip aheadtCtrl-K"), Other = wxPorting.T("Avanza OrologiotCtrl-K") },
 	new LocalizeInfo() { English = wxPorting.T("S&tation scheduletF6"), Other = wxPorting.T("Orario StazionitF6") },
 	new LocalizeInfo() { English = wxPorting.T("Select ItinerarytCtrl-I"), Other = wxPorting.T("Scelta ItineraritCtrl-I") },
 	new LocalizeInfo() { English = wxPorting.T("Set sig. to green"), Other = wxPorting.T("Segnali autom. a verde") },
 	new LocalizeInfo() { English = wxPorting.T("&Performance"), Other = wxPorting.T("Prestazioni") },
 
 	new LocalizeInfo() { English = wxPorting.T("&View"), Other = wxPorting.T("&Mostra") },
 	new LocalizeInfo() { English = wxPorting.T("Show layouttF3"), Other = wxPorting.T("Mostra tracciatotF3") },
 	new LocalizeInfo() { English = wxPorting.T("Show scheduletF4"), Other = wxPorting.T("Mostra orariotF4") },
 	new LocalizeInfo() { English = wxPorting.T("Show info pagetF5"), Other = wxPorting.T("Mostra pagina informazionitF5") },
 	new LocalizeInfo() { English = wxPorting.T("Timetable in split window"), Other = wxPorting.T("Orario in riquadro") },
 	new LocalizeInfo() { English = wxPorting.T("Timetable in tabbed window"), Other = wxPorting.T("Orario in pannello") },
 	new LocalizeInfo() { English = wxPorting.T("Timetable in separate window"), Other = wxPorting.T("Orario in finestra separata") },
 	new LocalizeInfo() { English = wxPorting.T("Tool bar"), Other = wxPorting.T("Barra strumenti") },
 	new LocalizeInfo() { English = wxPorting.T("Status bar"), Other = wxPorting.T("Linea di stato") },
 	new LocalizeInfo() { English = wxPorting.T("Zoom in"), Other = wxPorting.T("Ingrandisci") },
 	new LocalizeInfo() { English = wxPorting.T("Zoom out"), Other = wxPorting.T("Rimpicciolisci") },
 	new LocalizeInfo() { English = wxPorting.T("Coord bars"), Other = wxPorting.T("Barre coordinate") },
 
 	new LocalizeInfo() { English = wxPorting.T("Welcome"), Other = wxPorting.T("Benvenuto") },
 	new LocalizeInfo() { English = wxPorting.T("WelcometF1"), Other = wxPorting.T("BenvenutotF1") },
 	new LocalizeInfo() { English = wxPorting.T("&Help"), Other = wxPorting.T("&Aiuto") },
 
 	new LocalizeInfo() { English = wxPorting.T("Tools"), Other = wxPorting.T("Strumenti") },
 	new LocalizeInfo() { English = wxPorting.T("Graph"), Other = wxPorting.T("Grafico") },
 	new LocalizeInfo() { English = wxPorting.T("Layout"), Other = wxPorting.T("Tracciato") },
 
 	new LocalizeInfo() { English = wxPorting.T("You recently played the following simulations:<br><br>"), Other = wxPorting.T("Scenari simulati di recente:<br><br>") },
 	new LocalizeInfo() { English = wxPorting.T("Clear"), Other = wxPorting.T("Azzera") },
 
 	new LocalizeInfo() { English = wxPorting.T("Remove all alerts from this list?"), Other = wxPorting.T("Azzera la lista degli avvertimenti?") },
 	new LocalizeInfo() { English = wxPorting.T("Show Canceled"), Other = wxPorting.T("Mostra Cancellati") },
 	new LocalizeInfo() { English = wxPorting.T("Track First Train"), Other = wxPorting.T("Segui Primo Treno Attivo") },
 	new LocalizeInfo() { English = wxPorting.T("Track Last Train"), Other = wxPorting.T("Segui Ultimo Treno Attivo") },
 	new LocalizeInfo() { English = wxPorting.T("Show/hide canceled trains from list"), Other = wxPorting.T("Mostra/nasconde dalla lista i treni che non circolano") },
 	new LocalizeInfo() { English = wxPorting.T("Automatically show first active train in list"), Other = wxPorting.T("Mostra automaticamente nella lista il primo treno attivo") },
 	new LocalizeInfo() { English = wxPorting.T("Automatically show last active train in list"), Other = wxPorting.T("Mostra automaticamente nella lista l'ultimo treno attivo") },
 
 	new LocalizeInfo() { English = wxPorting.T("Stations &List"), Other = wxPorting.T("&Lista Stazioni") },
 	new LocalizeInfo() { English = wxPorting.T("Stations and Entry/Exit Points"), Other = wxPorting.T("Stazioni e Punti di Ingresso/Uscita") },
 	new LocalizeInfo() { English = wxPorting.T("Station Name"), Other = wxPorting.T("Nome Stazione") },
 	new LocalizeInfo() { English = wxPorting.T("Coordinates"), Other = wxPorting.T("Coordinate") },
 	new LocalizeInfo() { English = wxPorting.T("Entry/Exit"), Other = wxPorting.T("Ingresso/Uscita") },
         new LocalizeInfo() { English = wxPorting.T("Blocked by :"), Other = wxPorting.T("Bloccato da:") },
 
 	new LocalizeInfo() { English = wxPorting.T("### spiegazioni delle voci di menu'") },
 
 	new LocalizeInfo() { English = wxPorting.T("Open a simulation file."), Other = wxPorting.T("Apre uno scenario.") },
 	new LocalizeInfo() { English = wxPorting.T("Open a saved simulation file."), Other = wxPorting.T("Apre uno scenario salvato precedentemente.") },
 	new LocalizeInfo() { English = wxPorting.T("Restore from the last saved state."), Other = wxPorting.T("Ricarica l'ultimo scenario salvato.") },
 	new LocalizeInfo() { English = wxPorting.T("Changes the page layout settings."), Other = wxPorting.T("Cambia le opzioni della pagina tracciato.") },
 	new LocalizeInfo() { English = wxPorting.T("Preview print output."), Other = wxPorting.T("Visione bozza di stampa.") },
 	new LocalizeInfo() { English = wxPorting.T("Print all or part of the document."), Other = wxPorting.T("Stampa tutto o parte del documento.") },
 	new LocalizeInfo() { English = wxPorting.T("Quit this program."), Other = wxPorting.T("Esci dal programma.") },
 	new LocalizeInfo() { English = wxPorting.T("Enter/exit layout editor."), Other = wxPorting.T("Entra/esce dall'editor del tracciato.") },
 	new LocalizeInfo() { English = wxPorting.T("Enter/exit itinerary editor."), Other = wxPorting.T("Entra/esce dall'editor itinerari.") },
 	new LocalizeInfo() { English = wxPorting.T("Save changes to the layout."), Other = wxPorting.T("Salva le modifiche al tracciato.") },
 	new LocalizeInfo() { English = wxPorting.T("Change program's preferences."), Other = wxPorting.T("Modifica delle preferenze.") },
 	new LocalizeInfo() { English = wxPorting.T("Erase the layout."), Other = wxPorting.T("Azzera il tracciato.") },
 	new LocalizeInfo() { English = wxPorting.T("Show information about the scenario."), Other = wxPorting.T("Mostra informazioni relative allo scenario.") },
 	new LocalizeInfo() { English = wxPorting.T("Show list of stations and entry points."), Other = wxPorting.T("Lista le stazioni e i punti di ingresso/uscita") },
 	new LocalizeInfo() { English = wxPorting.T("Start/stop the simulation."), Other = wxPorting.T("Fa partire/ferma la simulazione.") },
 	new LocalizeInfo() { English = wxPorting.T("Show the timetable graph."), Other = wxPorting.T("Mostra il grafico orario.") },
 	new LocalizeInfo() { English = wxPorting.T("Show accumulation of late minutes over time."), Other = wxPorting.T("Mostra il grafico ritardi.") },
 	new LocalizeInfo() { English = wxPorting.T("Restart the simulation."), Other = wxPorting.T("Fa ripartire la simulazione.") },
 	new LocalizeInfo() { English = wxPorting.T("Speed up the simulation."), Other = wxPorting.T("Accelera la velocita' di simulazione.") },
 	new LocalizeInfo() { English = wxPorting.T("Slow down the simulation."), Other = wxPorting.T("Rallenta la velocita' di simulazione.") },
 	new LocalizeInfo() { English = wxPorting.T("Skip to 3 minutes before next event."), Other = wxPorting.T("Avanza la simulazione a 3 minuti prima del prossimo evento.") },
 	new LocalizeInfo() { English = wxPorting.T("Show the train schedule of each station."), Other = wxPorting.T("Mostra l'orario per stazione.") },
 	new LocalizeInfo() { English = wxPorting.T("Set all automatic signals to green."), Other = wxPorting.T("Poni tutti i segnali automatici a verde.") },
 	new LocalizeInfo() { English = wxPorting.T("Select an itinerary by name."), Other = wxPorting.T("Sceglie un itinerario usandone il nome.") },
 	new LocalizeInfo() { English = wxPorting.T("Show performance data."), Other = wxPorting.T("Mostra la tabella delle penalita'.") },
 	new LocalizeInfo() { English = wxPorting.T("Forcibly show the layout window."), Other = wxPorting.T("Mostra la finestra del tracciato.") },
 	new LocalizeInfo() { English = wxPorting.T("Forcibly show the schedule window."), Other = wxPorting.T("Mostra la finestra dell'orario.") },
 	new LocalizeInfo() { English = wxPorting.T("Shows the scenario info page, if available."), Other = wxPorting.T("Mostra la pagina di informazioni dello scenario, se presente.") },
 	new LocalizeInfo() { English = wxPorting.T("View timetable in a split window."), Other = wxPorting.T("Mostra l'orario in un riquadro.") },
 	new LocalizeInfo() { English = wxPorting.T("View timetable in a tab of the main window."), Other = wxPorting.T("Mostra l'orario nella finestra principale.") },
 	new LocalizeInfo() { English = wxPorting.T("View timetable in a window separate from the main window."), Other = wxPorting.T("Mostra l'orario in una finestra separata.") },
 	new LocalizeInfo() { English = wxPorting.T("Draw the layout at double the resolution."), Other = wxPorting.T("Disegna il tracciato a grandezza raddoppiata.") },
 	new LocalizeInfo() { English = wxPorting.T("Draw the layour at normal resolution."), Other = wxPorting.T("Disegna il tracciato a grandezza naturale.") },
 	new LocalizeInfo() { English = wxPorting.T("View/hide the coordinate bars."), Other = wxPorting.T("Mostra/nasconde le barre delle coordinate.") },
 	new LocalizeInfo() { English = wxPorting.T("View/hide the tools bar."), Other = wxPorting.T("Mostra/nasconde la barra strumenti.") },
 	new LocalizeInfo() { English = wxPorting.T("View/hide the status bar."), Other = wxPorting.T("Mostra/nasconde la linea di stato.") },
 	new LocalizeInfo() { English = wxPorting.T("Show the welcome page."), Other = wxPorting.T("Mostra la pagina di benvenuto.") },
 	new LocalizeInfo() { English = wxPorting.T("Show the copyright notice."), Other = wxPorting.T("Mostra la pagina di copyright.") },
 	new LocalizeInfo() { English = wxPorting.T("Open another simulation"), Other = wxPorting.T("Apri una nuova simulazione") },
 	new LocalizeInfo() { English = wxPorting.T("Create a new simulation"), Other = wxPorting.T("Crea una nuova simulazione") },
 	new LocalizeInfo() { English = wxPorting.T("Select the language to be used next time Traindir is started."), Other = wxPorting.T("Sceglie il linguaggio da usare la prossima volta che Traindir e' eseguito.") },
 	new LocalizeInfo() { English = wxPorting.T("Swap head and tail icons"), Other = wxPorting.T("Scambia icone di testa e di coda") },
         new LocalizeInfo() { English = wxPorting.T("Cannot create directory '%s'. Try creating it manually."), Other = wxPorting.T("Non riesco a create la directory '%s'. Prova a crearla a mano.") },
         new LocalizeInfo() { English = wxPorting.T("Show train names instead of icons"), Other = wxPorting.T("Mostra i nomi dei treni al posto delle icone") },
         new LocalizeInfo() { English = wxPorting.T("Don't show train names colors"), Other = wxPorting.T("Non usare i colori nei nomi dei treni") },
 
         new LocalizeInfo() { English = wxPorting.T("Switch&board"), Other = wxPorting.T("Pulsantiera") },
         new LocalizeInfo() { English = wxPorting.T("Shows the switchboard editor."), Other = wxPorting.T("Mostra l'editor delle pulsantiere.") },
         new LocalizeInfo() { English = wxPorting.T("Switchboard"), Other = wxPorting.T("Pulsantiera") },
         new LocalizeInfo() { English = wxPorting.T("Use this screen to define the layout of a switchboard and which itineraries are shown in it."), Other = wxPorting.T("Usa questo schermo per definire la disposizione delle pulsantiere e quali itinerari mostrare.") },
         new LocalizeInfo() { English = wxPorting.T("Switchboards are accessed via an external web browser at the port"), Other = wxPorting.T("Le pulsantiere sono accessibili da un browser esterno alla porta") },
         new LocalizeInfo() { English = wxPorting.T("Open the switchboard in a browser."), Other = wxPorting.T("Apri la pulsantiera in un browser") },
         new LocalizeInfo() { English = wxPorting.T("Switchboards"), Other = wxPorting.T("Pulsantiere") },
         new LocalizeInfo() { English = wxPorting.T("change"), Other = wxPorting.T("cambia") },
         new LocalizeInfo() { English = wxPorting.T("New board"), Other = wxPorting.T("Nuova pulsantiera") },
         new LocalizeInfo() { English = wxPorting.T("No selected switchboard."), Other = wxPorting.T("Nessuna pulsantiera selezionata.") },
         new LocalizeInfo() { English = wxPorting.T("Switchboard Name"), Other = wxPorting.T("Nome Pulsantiera") },
         new LocalizeInfo() { English = wxPorting.T("&Visible Name:"), Other = wxPorting.T("Nome &Visibile:") },
         new LocalizeInfo() { English = wxPorting.T("&File name:"), Other = wxPorting.T("Nome &File:") },
         new LocalizeInfo() { English = wxPorting.T("&Remove"), Other = wxPorting.T("&Rimuovi") },
         new LocalizeInfo() { English = wxPorting.T("&Save"), Other = wxPorting.T("&Salva") },
         new LocalizeInfo() { English = wxPorting.T("&Label"), Other = wxPorting.T("&Dicitura") },
         new LocalizeInfo() { English = wxPorting.T("&Itinerary Name"), Other = wxPorting.T("Nome &Itinerario") },
 
         new LocalizeInfo() { English = wxPorting.T("Scenario Info"), Other = wxPorting.T("Informazioni Scenario") },
         new LocalizeInfo() { English = wxPorting.T("Saving now will lead to an invalid file. Please continue the simulation for a bit and try again."),
           Other = wxPorting.T("Salvare ora condurrebbe a un file errato. Si prega continuare la simulazione e riprovare piu' avanti.") },
 
 	null
    };
  }
}